################################################################################
#
# Title:        ONTAP-41-05 - Clone Volume
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2023-10-08
# Description:  Cloning (NFS)
#               - Clone Volume
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_cluster"
  name:                                "ONTAP-41-05 - Clone Volume"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create a snapshot on volume - "{{ ontap_41_vol_name }}"
      netapp.ontap.na_ontap_snapshot:
        state:                         present
        snapshot:                      "{{ ontap_41_snapshot_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume:                        "{{ ontap_41_vol_name }}"
        <<: *input

    - name: Create minimum Clone Junction Path Mountpoint
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ ontap_41_clone_dir_name }}"
        aggregate_name:                "{{ storage_aggregates[0].name }}"
        export_policy:                 "ro_{{ global_primary_nas_svm }}"
        junction_path:                 "/{{ ontap_41_clone_dir_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume_security_style:         "unix"
        <<: *input

    - name: Create Volume clone (Flexclone) - "{{ ontap_41_snapshot_name }}"
      netapp.ontap.na_ontap_volume_clone:
        state:                         present
        vserver:                       "{{ global_primary_nas_svm }}"
        parent_volume:                 "{{ ontap_41_vol_name }}"
        name:                          "{{ ontap_41_clone_vol_name}}"
        parent_snapshot:               "{{ ontap_41_snapshot_name }}"
        junction_path:                 "/{{ ontap_41_clone_dir_name }}/{{ ontap_41_clone_vol_name }}"
        <<: *input
  
  post_tasks: