################################################################################
#
# Title:        ONTAP-41-03 - Mount & Write (Origin Volume)
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2023-10-08
# Description:  Cloning (NFS)
#               - Mount & Write (Volume)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "linux"
  name:               "ONTAP-41-03 - Mount & Write (Origin Volume)"
  gather_facts:       false
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:
    - name: Get and Set Ansible date_time fact
      set_fact:
        pipe_timestamp: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"

  tasks:
    - name: Ensure stale mounts are removed before proceding (in case a mount exists)
      ansible.posix.mount:
        state:                      "absent"
        src:                        "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/\
                                     {{ ontap_41_vol_name }}"
        path:                       "{{ linux_default_mount_dir }}/{{ ontap_41_vol_name }}"
#        opts:                       "rw,sync,hard,vers=3"
        fstype:                     "nfs"
  
    - name: Create mount directories
      ansible.builtin.file:
        path:                       "{{ linux_41_mount_dir }}/{{ ontap_41_vol_name }}"
        state:                      "directory"
        mode:                       "0755"
  
    - name: Mount NFS export on Linux host
      ansible.posix.mount:
        state:                      "mounted"
        src:                        "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/\
                                     {{ ontap_41_vol_name }}"
        path:                       "{{ linux_41_mount_dir }}/{{ ontap_41_vol_name }}"
        # opts:                       "rw,sync,hard,vers=3"
        fstype:                     "nfs"
  
    - name: Create test file on NFS export
      community.general.filesize:
        path: "{{ linux_41_mount_dir }}/{{ ontap_41_vol_name }}/{{ ontap_41_snapshot_name }}_original_{{ pipe_timestamp }}"
        size: "{{ filesize | default('500MB') }}"
  
  post_tasks: