################################################################################
#
# Title:        ONTAP-41-08 - Clone & Write (Loop)
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2023-10-10
# Description:  Cloning (NFS)
#               - Clone & Write (Loop)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-41-08 - Clone & Write (Loop)"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    # - name: Output from index_var
    #   ansible.builtin.debug:
    #     # msg: "{{ ontap_41_clone_vol_name }}_{{ '%02x' | format(item) }}"
    #     msg: "{{ ontap_41_clone_vol_name }}_{{ '%02x' | format(my_idx + 1) }}"
    #   loop: "{{ range(1, 10) | list }}"
    #   loop_control:
    #     index_var: my_idx

    - name: Create & Mount Nine (9) NFS Clones from Source
      include_tasks: client_copy_n_mount.yml
      loop: "{{ range(1, 10) | list }}"
      loop_control:
        index_var: idx
  
  post_tasks: