################################################################################
#
# Title:        ONTAP-51-01 - Custom Policy
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Local Versioning (Snapshots)
#               - Custom Policy
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-51-01 - Custom Policy"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create custom snapshot policy
      netapp.ontap.na_ontap_snapshot_policy:
        state:                         present
        vserver:                       "{{ global_primary_nas_svm }}"
        name:                          "{{ ontap_51_snap_policy_name }}"
        schedule:                      "10min"
        prefix:                        "10min_"
        count:                         6
        enabled:                       True

  post_tasks: