################################################################################
#
# Title:        ONTAP-51-03 - Snapshot
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Snapshot
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-51-03 - Create Snapshot"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create snapshot
      netapp.ontap.na_ontap_snapshot:
        state:                         present
        snapshot:                      "{{ ontap_51_snapshot_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume:                        "{{ ontap_51_vol_name }}"
        comment:                       "ONTAP Test 51"

  post_tasks: