################################################################################
#
# Title:        ONTAP-51-03 - Create Snapshot
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Create Snapshot
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-52-03 - Create Snapshot"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create snapshot
      netapp.ontap.na_ontap_snapshot:
        state:                         present
        snapshot:                      "{{ ontap_51_snapshot_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume:                        "{{ ontap_51_vol_name }}"
        comment:                       "ONTAP Test 51"
        <<: *input

  post_tasks: