################################################################################
#
# Title:        ONTAP-51-04 - Delete Files
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Delete Files
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "linux"
  name:                                "ONTAP-51-04 - Delete Files - Linux"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:

  tasks:
    - name: Delete some test files
      ansible.builtin.file:
        state:                         absent
        path:                          "{{ linux_51_mount_dir }}/\
                                        {{ ontap_51_lin_qtree_name }}/\
                                        {{ item }}"
      loop:
        - "testfile01"
        - "testfile02"
        - "testfile03"
  
  post_tasks:

- hosts:                               "windows_hosts"
  name:                                "ONTAP-51-04 - Delete Files - Windows"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Delete some test files
      ansible.windows.win_file:
        path:                          "\\\\{{ global_primary_nas_svm }}\\{{ ontap_51_win_qtree_name}}\\{{ item }}"
        state:                         absent
      loop:
        - "testfile01"
        - "testfile02"
        - "testfile03"
      vars:
        ansible_become:                "yes"
        ansible_become_method:         "runas"
        ansible_become_user:           "{{ ansible_user }}"
        ansible_become_pass:           "{{ ansible_password }}"

  post_tasks: