################################################################################
#
# Title:        ONTAP-15-02 - Peering
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-03
# Description:  Cluster Peering
#               - Peering
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-15-02 - Peering"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/{{ inventory_dir }}/vars.yml
    - ../../vars/{{ inventory_dir }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create peerings
      netapp.ontap.na_ontap_cluster_peer:
        state:                         present
        source_intercluster_lifs:      "{{ item.local_network.interfaces | map(attribute='ip_address') | flatten }}"
        dest_intercluster_lifs:        "{{ item.remote.ip_addresses }}"
        passphrase:                    "{{ item.authentication.passphrase }}"
        peer_options:
          hostname:                    "{{ item.name }}"
        encryption_protocol_proposed:  "{{ item.encryption.proposed }}"
        <<: *input
      loop:
        "{{ cluster_peers }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name is defined

  post_tasks: