################################################################################
#
# Title:        ONTAP-80-01 - Modify Local Versioning
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2025-02-13
# Description:  Advanced - Self-Service
#               - Modify Local Versioning
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################


- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-80-01 - Modify Local Versioning"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Modify volume snapshot policy
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ request_volume }}"
        snapshot_policy:               "{{ service_value }}"
        junction_path:                 "/{{ item.1 }}"
        vserver:                       "{{ request_svm }}"

  post_tasks: