collections:
  - name:     "netapp.ontap"
    version:  "22.14.0"
  - name:     "ansible.utils"
    version:  "5.1.2"
  - name:     "ansible.posix"
    version:  "1.6.2"
  - name:     "ansible.windows"
    version:  "2.7.0"
  - name:     "community.windows"
    version:  "2.3.0"
  - name:     "microsoft.ad"
    version:  "1.8.0"
  - name:     "community.general"
    version:  "10.4.0"
  - name:     "ansible.eda"
    version:  "2.5.0"
