################################################################################
#
# Title:        ONTAP-10-03 - Network Services 
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Basic Cluster Configuration
#               - Network Services
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "ontap"
  name:                                "ONTAP-10-03 - Network Services"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create DNS config on storage cluster
      netapp.ontap.na_ontap_dns:
        state:                         present
        vserver:                       "{{ inventory_hostname }}"
        domains:                       "{{ all_dns_domains }}"
        nameservers:                   "{{ all_dns_nameservers }}"
        use_rest:                      "never"
  
    - name: Create NTP server on storage cluster
      netapp.ontap.na_ontap_ntp:
        state:                         present
        server_name:                   "{{ item }}"
        version:                       "auto"
      loop:
        "{{ all_ntp_serveres }}"
      retries: 10
      delay: 3
      register: result
      until: not result.failed

  post_tasks: