################################################################################
#
# Title:        ONTAP-10-04 - Storage Aggregates 
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Basic Cluster Configuration
#               - Aggregates
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "ontap"
  name:                                "ONTAP-10-04 - Storage Aggregates"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create data aggregates on storage cluster 
      netapp.ontap.na_ontap_aggregate:
        state:                         present
        name:                          "{{ item.name }}"
        nodes:                         "{{ item.node.name }}"
        disk_count:                    "{{ item.block_storage.primary.disk_count }}"
        snaplock_type:                 "{{ item.snaplock_type }}"
      loop:
        "{{ storage_aggregates }}"
      loop_control:
        label: "{{ item.node.name }}:{{ item.name }}"
      when:
        - item.name is defined

  post_tasks: