ansible_connection:               "local"
ansible_python_interpreter:       "{{ansible_playbook_python}}"

network_ethernet_broadcast_domains:
  - name:                         "bc_data"
    ipspace:
      name:                       "Default"
    mtu:                          1500