################################################################################
#
# Title:        BSS-08-04.yml
# Author:       NetApp. Inc (badrian)
# Date:         2023-08-02
# Description:  Change volume size (increase & decrease)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
#
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               BSS-08-04
  gather_facts:       false
  vars:
    input_01: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - size
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_vols.ontap_info.storage_volumes.records }}"

  tasks:
  - name: Increase FlexVol size
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_08_mixed_vol_name }}"
      size:                       "{{ ontap_default_fg_size_gb + ontap_default_fg_size_increment_gb }}"
      size_unit:                  gb
      vserver:                    "{{ ontap_primary_nas_svm }}"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - size
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_vols.ontap_info.storage_volumes.records }}"
  
  - name: Decrease FlexVol size
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_08_mixed_vol_name }}"
      size:                       "{{ ontap_default_fg_size_gb }}"
      size_unit:                  gb
      vserver:                    "{{ ontap_primary_nas_svm }}"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  post_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - size
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: post_ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ post_ontap_vols.ontap_info.storage_volumes.records }}"