################################################################################
#
# Title:        BSS-08-07.yml
# Author:       NetApp. Inc (badrian)
# Date:         2023-08-02
# Description:  Remove "masking" from volume (removing share and export policy)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
# ansible-doc netapp.ontap.na_ontap_cifs
#
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               BSS-08-07 - Storage Play
  gather_facts:       false
  vars:
    input_01: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_vols.ontap_info.storage_volumes.records }}"

  - name: Get all CIFS shares
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - protocols/cifs/shares
      fields:
        - name
      parameters:
        name: "!ipc$,!c$"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_cifs

  - name: Show all shares
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_cifs.ontap_info.protocols_cifs_shares.records }}"

  tasks:
  - name: Removing "Masking" - changing export policy
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_08_mixed_vol_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      export_policy:              "default"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Removing CIFS share
    netapp.ontap.na_ontap_cifs:
      state:                      absent
      name:                       "{{ ontap_08_share_name }}"
      path:                       "/{{ ontap_08_mixed_vol_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  post_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_vols.ontap_info.storage_volumes.records }}"

  - name: Get all CIFS shares
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - protocols/cifs/shares
      fields:
        - name
      parameters:
        name: "!ipc$,!c$"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_cifs

  - name: Show all shares
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_cifs.ontap_info.protocols_cifs_shares.records }}"