################################################################################
#
# Title:        ONTAP-00-01.yml
# Author:       NetApp Inc. (badrian)
# Date:         2023-07-25
# Description:  Initial cluster configuration for testing
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc <module.name>
# 
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               ONTAP-00-01
  gather_facts:       false
  vars_prompt:
    - name:           testenv_ad_join_pw
      prompt:         "Please enter password for user  {{ testenv_ad_join_user }}"
      private:        true
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Create ro export policy (aka "storage group") for SVM root volume
    netapp.ontap.na_ontap_export_policy:
      state:                      present
      name:                       "ro_{{ item.name }}"
      vserver:                    "{{ item.name }}"
      hostname:                   "{{ ontap_hostname }}"
      use_rest:                   "always"
      <<: *input
    loop:
      "{{ ontap_svms }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Create ro export policy rules for SVM root volume
    na_ontap_export_policy_rule:
      state:                      present
      name:                       "ro_{{ item.name }}"
      vserver:                    "{{ item.name }}"
      client_match:               "0.0.0.0/0"
      ro_rule:                    "any"
      rw_rule:                    "none"
      protocol:                   "nfs"
      super_user_security:        "none"
      allow_suid:                 false
      hostname:                   "{{ ontap_hostname }}"
      use_rest:                   "always"
      <<: *input
    loop:
      "{{ ontap_svms }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Apply RO export policy to SVM root volume
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ item.name.replace('-','_') }}_root"
      vserver:                    "{{ item.name }}"
      export_policy:              "ro_{{ item.name }}"
      hostname:                   "{{ ontap_hostname }}"
      use_rest:                   "always"
      <<: *input
    loop:
      "{{ ontap_svms }}"
    loop_control:
      label: "{{ item.name }}" 