################################################################################
#
# Title:        BSS-06-01.yml
# Author:       NetApp. Inc (shatfield)
# Date:         2023-08-01
# Description:  Create test volumes (FlexGroups) for BSS-06
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_export_policy
# ansible-doc netapp.ontap.na_ontap_export_policy_rule
# ansible-doc netapp.ontap.na_ontap_volume
# ansible-doc netapp.ontap.na_ontap_cifs
#
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               BSS-06-01
  gather_facts:       false
  vars:
    input_01: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_vols.ontap_info.storage_volumes.records }}"

  - name: Get all export policies
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - protocols/nfs/export-policies
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_policies

  - name: Show all export policies
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_policies.ontap_info.protocols_nfs_export_policies.records }}"

  tasks:
  - name: Create export policy (aka "storage group")
    netapp.ontap.na_ontap_export_policy:
      state:                      present
      name:                       "{{ ontap_06_policy_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Create export policy rules
    netapp.ontap.na_ontap_export_policy_rule:
      state:                      present
      name:                       "{{ ontap_06_policy_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      client_match:               "{{ testenv_lin_hosts }}"
      ro_rule:                    "any"                    
      rw_rule:                    "any"
      protocol:                   "nfs"
      super_user_security:        "any"
      allow_suid:                 true
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Create FlexGroup for Linux Host
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_06_lin_vol_name }}"
      size:                       "{{ ontap_default_fg_size_gb }}"
      volume_security_style:      "unix"
      aggr_list:
      - "{{ ontap_primary_cluster_aggr01 }}"
      - "{{ ontap_primary_cluster_aggr02 }}"
      aggr_list_multiplier:       "{{ ontap_default_fg_multiplier }}"
      size_unit:                  gb
      space_guarantee:            "none"
      tiering_policy:             "auto"
      export_policy:              "{{ ontap_06_policy_name }}"
      junction_path:              "/{{ ontap_06_lin_vol_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Create FlexGroup for Windows host
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_06_win_vol_name }}"
      size:                       "{{ ontap_default_fg_size_gb }}"
      volume_security_style:      "ntfs"
      aggr_list:
      - "{{ ontap_primary_cluster_aggr01 }}"
      - "{{ ontap_primary_cluster_aggr02 }}"
      aggr_list_multiplier:       "{{ ontap_default_fg_multiplier }}"
      size_unit:                  gb
      space_guarantee:            "none"
      tiering_policy:             "auto"
      junction_path:              "/{{ ontap_06_win_vol_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Create a test share
    netapp.ontap.na_ontap_cifs:
      state:                      present
      name:                       "{{ ontap_06_share_name }}"
      path:                       "/{{ ontap_06_win_vol_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      browsable:                  true
      oplocks:                    true
      show_snapshot:              true
      show_previous_versions:     true
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  post_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_vols.ontap_info.storage_volumes.records }}"

  - name: Get all export policies
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - protocols/nfs/export-policies
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_policies

  - name: Show all export policies
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_policies.ontap_info.protocols_nfs_export_policies.records }}"
