- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ontap_webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: ARP Snapshot Event from Primary Cluster
      condition:
        all:
          - event.payload.netapp['ems-message-info'].message-name == "arp.snapshot.created"

  ## Define the action we should take should the condition be met

      action:
        run_playbook:
          name: playbooks/ONTAP-83/ONTAP-83-05.yml
          extra_vars:
             svm_name: "{{ event.payload.netapp['ems-message-info'].parameters.parameter | 
                           selectattr('name', 'match', 'vserverName') | 
                           map(attribute='value') | 
                           first}}"