- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ontap_webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: ARP Snapshot Event from Primary Cluster
      condition:
        all:
          - event.payload.netapp['ems-message-info'].message-name == "arp.snapshot.created"
          - event.payload.netapp['ems-message-info'].parameters == "sp-svm-astrainc"

  ## Define the action we should take should the condition be met

      action:
        run_playbook:
          name: playbooks/ONTAP-01/ONTAP-01-04.yml