- name: Listen for events on an ONTAP webhook
  hosts: all

  sources:
    - ontap_webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: ARP Snapshot Event from Primary Cluster
      condition:
        all:
          - event.payload.netapp['ems-message-info']['message-name'] == "arw.snapshot.created"
          - event.payload.netapp['ems-message-info'].parameters.parameter | selectattr('name', 'eq', 'vserverName') | map(attribute='value') | first == "sp-svm-astrainc"

      action:
        run_playbook:
          name: playbooks/ONTAP-83/ONTAP-83-05.yml
          extra_vars:
             svm_name: "{{ event.payload.netapp['ems-message-info'].parameters.parameter | 
                           selectattr('name', 'eq', 'vserverName') | 
                           map(attribute='value') | 
                           first}}"