- name: Listen for events on an ONTAP webhook
  hosts: all

  sources:
    - ontap_webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: ARP Snapshot Event from Primary Cluster
      condition: event.payload.netapp['ems-message-info'].message-name is defined 

      action:
        debug:
          msg: "{{ event.payload.netapp['ems-message-info'].message-name }}"
#        run_playbook:
#          name: playbooks/ONTAP-83/ONTAP-83-05.yml
#          extra_vars:
#             svm_name: "{{ event.payload.netapp['ems-message-info'].parameters.parameter | 
#                           selectattr('name', 'eq', 'vserverName') | 
#                           map(attribute='value') | 
#                           first}}"