- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ontap_webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Any notice from ONTAP
      condition: event.payload.netapp['ems-message-info'].severity == "notice"

  ## Define the action we should take should the condition be met

      action:
        run_playbook:
          name: playbooks/ONTAP-01/ONTAP-01-04.yml