################################################################################
#
# Title:        ONTAP-self-arp-81 - Modify Ransomware Protection
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2025-03-06
# Description:  Advanced - Self-Service
#               - Modify Ransomware Protection
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################


- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-self-arp-81 - Modify Ransomware Protections"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Modify Anti-ransomware Protection on Volume
      netapp.ontap.na_ontap_rest_cli:
        command:                       "security/anti-ransomware/volume/{{ 'enable' if request_service_value == 'enabled' else 'disable' }}"
        verb:                          "POST"
        params:
        body:
          vserver:                     "{{ request_svm }}"
          volume:                      "{{ request_volume }}"
      ignore_errors:                   true

    - name: Activate additional notifications for ransomware events
      netapp.ontap.na_ontap_rest_cli:
        command:                       "security/anti-ransomware/volume/event-log"
        verb:                          "PATCH"
        params:
          vserver:                     "{{ request_svm }}"
          volume:                      "{{ request_volume }}"
        body:
          is-enabled-on-new-file-extension-seen:
                                       true
          is-enabled-on-snapshot-copy-creation:
                                       true
      when:
        - request_service_value == "enabled"

  post_tasks: