################################################################################
#
# Title:        ONTAP-81-eda-rulebook - React to attack
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2025-02-25
# Description:  Advanced - Anti-Ransomware
#               - Start Event-driven Ansible with custom webhook for ONTAP
#               - React to anti-ransomware snapshot creation and take SVM's
#                 network LIFs down
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- name:                           Listen for events on an ONTAP webhook
  hosts:                          ontap

  sources:
    - ontap_webhook:
        host:                     0.0.0.0
        port:                     5000

  rules:
    - name: ARP Snapshot Event from Primary Cluster
      condition: event.payload.netapp['ems-message-info']['message-name'] == "arw.snapshot.created"

      action:
        run_playbook:
          name: playbooks/ONTAP-81/eda/ONTAP-81-eda-01.yml
          extra_vars:
             svm_name: "{{ event.payload.netapp['ems-message-info'].parameters.parameter | 
                           selectattr('name', 'eq', 'vserverName') | 
                           map(attribute='value') | 
                           first}}"