################################################################################
#
# Title:        ONTAP-11-04 - Event Notification
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Advanced Cluster Configuration
#               - Event Notification
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "ontap"
  name:                                "ONTAP-11-04 - Event Notification"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:  
    - name: Configure REST EMS destination
      netapp.ontap.na_ontap_ems_destination:
        state:                         "present"
        name:                          "{{ item.name }}"
        type:                          "{{ item.type }}"
        filters:                       "{{ item.filters }}"
        destination:                   "{{ item.destination }}"
        <<: *input
      loop:
        "{{ support.ems.destinations }}"