################################################################################
#
# Title:        ONTAP-37-02 - Namespaces
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-11-22
# Description:  NVMe/TCP
#               - Namespaces
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-37-02 - Namespaces"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create LUNs
      netapp.ontap.na_ontap_nvme_namespace:
        state:                         present
        vserver:                       "{{ global_primary_san_svm }}"
        path:                          "{{ item }}"
        size:                          "{{ ontap_default_lun_size_gb }}"
        size_unit:                     "gb"
        ostype:                        "linux"
      loop:
        "{{ ontap_37_lin_namespaces }}"

  post_tasks: