################################################################################
#
# Title:        ONTAP-37-03 - Subsystem
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-11-22
# Description:  NVMe/TCP
#               - Subsystem
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "linux"
  name:                                "ONTAP-37-03 - Subsystem - Linux"
  gather_facts:                        true
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - community.general
    - ansible.posix

  pre_tasks:

  tasks:

  post_tasks:
  

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-37-03 - Subsystem - ONTAP"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create a Subsystem
      netapp.ontap.na_ontap_nvme_subsystem:
        state:                         present
        vserver:                       "{{ global_primary_san_svm }}"
        subsystem:                     "{{ ontap_37_lin_subsystem_name }}"
        ostype:                        "linux"
        hosts:                         "{{ hostvars[groups['linux_hosts'][0]].ansible_hostnqn }}"
        paths:                         "{{ ontap_37_lin_namespaces }}"

  post_tasks: