################################################################################
#
# Title:        ONTAP-37-01 - Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-11-22
# Description:  NVMe/TCP
#               - Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-37-01 - Volumes"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create volumes
      netapp.ontap.na_ontap_volume:
        state:                    present
        name:                     "{{ (item | split('/'))[2] }}"
        aggregate_name:           "{{ hostvars[global_primary_test_cluster].storage_aggregates[1].name }}"
        size:                     "{{ ontap_default_vol_size_gb }}"
        size_unit:                gb
        space_guarantee:          none
        tiering_policy:           auto
        vserver:                  "{{ global_primary_san_svm }}"
        <<: *input
      loop:
        "{{ ontap_37_lin_namespaces }}"
  
  post_tasks: