################################################################################
#
# Title:        ONTAP-83-02 - Configure Events
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-11-04
# Description:  Anti-Ransomware
#               - Configure Events
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-83-02 - Configure Events"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Configure EMS filters for every tenant
      netapp.ontap.na_ontap_ems_filter:
        state:                         "present"
        name:                          "ems_{{ item }}"
        rules:                         []
      loop:
        "{{ ontap_80_svms }}"

    - name: Add EMS filter to match tenant only
      netapp.ontap.na_ontap_rest_cli:
        command:                       'event/filter/rule/add'
        verb:                          'POST'
        params:
        body:
          filter-name:                 "ems_{{ item }}"
          type:                        "include"
          position:                    1
          message-name:                "arw.*"
          severity:
            - "*"
          parameter-criteria:
            - "vserverName={{ item }}"
      loop:
        "{{ ontap_80_svms }}"

    - name: Configure REST EMS destination for every tenant
      netapp.ontap.na_ontap_ems_destination:
        state:                         "present"
        name:                          "dest_{{ item }}"
        type:                          "{{ ontap_83_ems_dest_type }}"
        filters:                       "ems_{{ item }}"
        destination:                   "{{ ontap_83_ems_dest_destination }}{{ item }}"
      loop:
        "{{ ontap_80_svms }}"

      # Add special webhook for event driven Ansible on one SVM
    - name: Configure EMS filters for EDA on {{ ontap_80_svms[1] }}
      netapp.ontap.na_ontap_ems_filter:
        state:                         "present"
        name:                          "ems_arp_eda_{{ ontap_80_svms[1] }}"
        rules:                         []

    - name: Add EMS filter to match {{ ontap_80_svms[1] }} and ARP Snapshot Create only
      netapp.ontap.na_ontap_rest_cli:
        command:                       'event/filter/rule/add'
        verb:                          'POST'
        params:
        body:
          filter-name:                 "ems_arp_eda_{{ ontap_80_svms[1] }}"
          type:                        "include"
          position:                    1
          message-name:                "arw.snapshot.created"
          severity:
            - "*"
          parameter-criteria:
            - "vserverName={{ ontap_80_svms[1] }}"

    - name: Configure REST EMS destination for EDA on {{ ontap_80_svms[1] }}
      netapp.ontap.na_ontap_ems_destination:
        state:                         "present"
        name:                          "dest_eda_{{ ontap_80_svms[1] }}"
        type:                          "{{ ontap_83_ems_dest_type }}"
        filters:                       "ems_{{ item }}"
        destination:                   "{{ ontap_83_ems_eda_dest_destination }}{{ item }}"

  post_tasks: