################################################################################
#
# Title:        ONTAP-33-01 - User and Group
# Author:       NetApp Inc. (jont)
# Initial
# Create Date:  2025-04-10
# Description:  S3
#               - User and Group
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "site01_ontap"
  name:                                "ONTAP-33-01 - User and Group"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create or regenerate the S3 user
      netapp.ontap.na_ontap_s3_users:
        state:                         present
        name:                          "{{ ontap_33_s3_user_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        regenerate_keys:               true
      register: s3_user
  
    - name: Add SVM name to credential details
      ansible.builtin.set_fact:
        s3_user:                       "{{ ({global_primary_nas_svm: s3_user}) }}"

    - name: Print user details
      debug:
        var: s3_user

    - name: Create S3 Group with full access
      netapp.ontap.na_ontap_s3_groups:
        state:                         present
        name:                          "{{ ontap_33_s3_group_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        users:
          - name:                      "{{ ontap_33_s3_user_name }}"
        policies:
          - name:                      "FullAccess"

  post_tasks:

- hosts:                               "linux_hosts"
  name:                                "ONTAP-33-01 - User and Group - Linux"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Create directory for S3 credentials
      ansible.builtin.file:
        state:                         directory
        path:                          "{{ linux_default_mount_dir }}/.s3_credentials/"

    - name: Create credential file for S3 User
      ansible.builtin.copy:
        content:                       "{{ hostvars['cluster1'].s3_user | to_nice_json }}"
        dest:                          "{{ linux_default_mount_dir }}/.s3_credentials/{{ global_primary_nas_svm }}.json"
      when:
        - hostvars['cluster1'].s3_user is defined

  post_tasks:


- hosts:                               "windows_hosts"
  name:                                "ONTAP-33-01 - User and Group - Windows"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Create directory for S3 credentials
      ansible.windows.win_file:
        path:                          "{{ windows_default_mount_dir }}\\s3_credentials"
        state:                         directory

    - name: Remove existing credential files
      ansible.windows.win_file:
        state:                         absent
        path:                          "{{ windows_default_mount_dir }}\\s3_credentials\\{{ global_primary_nas_svm }}.json"
      when:
        - hostvars['cluster1'].s3_user is defined

    - name: Write credentials to files
      community.windows.win_lineinfile:
        state:                         present
        path:                          "{{ windows_default_mount_dir }}\\s3_credentials\\{{ global_primary_nas_svm }}.json"
        create:                        true
        line:                          "{{ hostvars['cluster1'].s3_user | to_nice_json }}"
      when:
        - hostvars['cluster1'].s3_user is defined

  post_tasks:
