cluster:
  - name:                         "cluster1"

cluster_nodes:
  - name:                         "cluster1-01"
    location:                     "Virtual DC01 | Virtual Rack 01"
  - name:                         "cluster1-02"
    location:                     "Virtual DC01 | Virtual Rack 02"

cluster_licensing_licenses: []

network_ethernet_ports:
  - name:                         "a0a"
    node:
      name:                       "{{ cluster_nodes[0].name }}"
    lag:
      member_ports:
        - name:                   "e0f"
        - name:                   "e0g"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_data"
      ipspace:
        name:                     "Default"
    type:                         "lag"
  - name:                         "a0a"
    node:
      name:                       "{{ cluster_nodes[1].name }}"
    lag:
      member_ports:
        - name:                   "e0f"
        - name:                   "e0g"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_data"
      ipspace:
        name:                     "Default"
    type:                         "lag"

storage_aggregates:
  - name:                         "{{ cluster_nodes[0].name }}_aggr01"
    node:
      name:                       "{{ cluster_nodes[0].name }}"
    block_storage:
      primary:
        disk_count:               13
    snaplock_type:                "non_snaplock"
  - name:                         "{{ cluster_nodes[1].name }}_aggr01"
    node:
      name:                       "{{ cluster_nodes[1].name }}"
    block_storage:
      primary:
        disk_count:               13
    snaplock_type:                "non_snaplock"

svm_svms:
  - name:                         "ntap-nas-svm01"
    dns:
      domains:                    "{{ testenv_default_dns_domain }}"
      servers:                    "{{ testenv_dns_nameservers }}"
    auto_enable_analytics:        true
    ipspace:
      name:                       "Default"
    nfs:
      allowed:                    true
    cifs:
      allowed:                    true
    iscsi:
      allowed:                    false
    fcp:
      allowed:                    false
    ndmp:
      allowed:                    false
    nvme:
      allowed:                    false
    language:                     "utf8mb4"
    comment:                      "This is the primary NAS SVM for testing"
  - name:                         "ntap-nas-svm02"
    dns:
      domains:                    "{{ testenv_default_dns_domain }}"
      servers:                    "{{ testenv_dns_nameservers }}"
    auto_enable_analytics:        true
    ipspace:
      name:                       "Default"
    nfs:
      allowed:                    true
    cifs:
      allowed:                    true
    iscsi:
      allowed:                    false
    fcp:
      allowed:                    false
    ndmp:
      allowed:                    false
    nvme:
      allowed:                    false
    language:                     "utf8mb4"
    comment:                      "This is the secondary NAS SVM for testing"

protocols_cifs_services:
  - name:                         "nas-svm01"
    svm:
      name:                       "{{ svm_svms[0].name }}"
    ad_domain:
      fqdn:                       "{{ testenv_ad_domain }}"
      organizational_unit":       "{{ testenv_storage_ad_ou_path }}"
    comment:                      "This CIFS Server is the primary NAS server"
    enabled:                      true
  - name:                         "nas-svm02"
    svm:
      name:                       "{{ svm_svms[1].name }}"
    ad_domain:
      fqdn:                       "{{ testenv_ad_domain }}"
      organizational_unit":       "{{ testenv_storage_ad_ou_path }}"
    comment:                      "This CIFS Server is the secondary NAS server"
    enabled:                      true

protocols_nfs_services:
  - svm:
      name: "svm1"
    enabled:                      true
    protocol:
      v3_enabled:                 true
      v40_enabled:                false
      v41_enabled:                false
      v3_64bit_identifiers_enabled: true
    showmount_enabled:            true

network_ip_interfaces:
  - name:                         "{{ svm_svms[0].name }}"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[0].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.211"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      failover:                   "default"
      auto_revert:                true
    ipspace:
      name:                       "Default"
    service_policy:
      name:                       "default-data-files"
  - name:                         "{{ svm_svms[1].name }}"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[1].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.221"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      failover:                   "default"
      auto_revert:                true
    ipspace:
      name:                       "Default"
    service_policy:
      name:                       "default-data-files"
  - name:                         "{{ cluster_nodes[0].name }}_ic01"
    scope:                        "cluster"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.121"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      failover:                   "default"
      auto_revert:                true
    ipspace:
      name:                       "Default"
    service_policy:
      name:                       "default-intercluster"
  - name:                         "{{ cluster_nodes[1].name }}_ic01"
    scope:                        "cluster"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.122"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      failover:                   "default"
      auto_revert:                true
    ipspace:
      name:                       "Default"
    service_policy:
      name:                       "default-intercluster"
