# Ansible Variables

# Custom Variables

# Variables basedon ONTAP REST model
# https://<ontap_cluster_mgmt>/docs/api
cluster:
  name:                           "cluster1"

cluster_nodes:
  - name:                         "cluster1-01"
    location:                     "Virtual DC01 | Virtual Rack 01"
  - name:                         "cluster1-02"
    location:                     "Virtual DC01 | Virtual Rack 02"

cluster_licensing_licenses: []

security_authentication_cluster_ad_proxy:
  svm:
    name:                        "{{ cluster.name }}_ad"       

network_ethernet_ports:
  - name:                         "a0a"
    node:
      name:                       "{{ cluster_nodes[0].name }}"
    type:                         "lag"
    lag:
      member_ports:
        - name:                   "e0f"
        - name:                   "e0g"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_data"
      ipspace:
        name:                     "Default"
  - name:                         "a0a"
    node:
      name:                       "{{ cluster_nodes[1].name }}"
    lag:
      member_ports:
        - name:                   "e0f"
        - name:                   "e0g"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_data"
      ipspace:
        name:                     "Default"
    type:                         "lag"
  - name:                         "a0b"
    node:
      name:                       "{{ cluster_nodes[0].name }}"
    type:                         "lag"
    lag:
      member_ports:
        - name:                   "e0d"
        - name:                   "e0e"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_peering"
      ipspace:
        name:                     "ip_peering"
  - name:                         "a0b"
    node:
      name:                       "{{ cluster_nodes[1].name }}"
    lag:
      member_ports:
        - name:                   "e0d"
        - name:                   "e0e"
      distribution_policy:        "port"
      mode:                       "singlemode"
    broadcast_domain:
      name:                       "bc_peering"
      ipspace:
        name:                     "ip_peering"
    type:                         "lag"

storage_aggregates:
  - name:                         "{{ cluster_nodes[0].name | replace('-','_') }}_aggr01"
    node:
      name:                       "{{ cluster_nodes[0].name }}"
    block_storage:
      primary:
        disk_count:               13
    snaplock_type:                "non_snaplock"
  - name:                         "{{ cluster_nodes[1].name | replace('-','_') }}_aggr01"
    node:
      name:                       "{{ cluster_nodes[1].name }}"
    block_storage:
      primary:
        disk_count:               13
    snaplock_type:                "non_snaplock"

svm_svms:
  - name:                         "{{ cluster.name }}_ad"
    dns:
      domains:                    "{{ all_dns_domains }}"
      servers:                    "{{ all_dns_nameservers }}"
    ipspace:
      name:                       "Default"
    nfs:
      allowed:                    false
    cifs:
      allowed:                    true
    iscsi:
      allowed:                    false
    fcp:
      allowed:                    false
    ndmp:
      allowed:                    false
    nvme:
      allowed:                    false
    language:                     "utf8mb4"
    comment:                      "This is the tunnel SVM for cluster AD authentication"
  - name:                         "ntap-svm01-nas"
    dns:
      domains:                    "{{ all_dns_domains }}"
      servers:                    "{{ all_dns_nameservers }}"
    auto_enable_analytics:        true
    auto_enable_activity_tracking: true
    ipspace:
      name:                       "Default"
    nfs:
      allowed:                    true
    cifs:
      allowed:                    true
    iscsi:
      allowed:                    false
    fcp:
      allowed:                    false
    ndmp:
      allowed:                    false
    nvme:
      allowed:                    false
    language:                     "utf8mb4"
    comment:                      "This is the first SVM for NAS testing"
  - name:                         "ntap-svm02-san"
    dns:
      domains:                    "{{ all_dns_domains }}"
      servers:                    "{{ all_dns_nameservers }}"
    auto_enable_analytics:        true
    auto_enable_activity_tracking: true
    ipspace:
      name:                       "Default"
    nfs:
      allowed:                    false
    cifs:
      allowed:                    true
    iscsi:
      allowed:                    true
    fcp:
      allowed:                    false
    ndmp:
      allowed:                    false
    nvme:
      allowed:                    true
    language:                     "utf8mb4"
    comment:                      "This is the second SVM for SAN testing"

protocols_nfs_services:
  - svm:
      name:                       "{{ svm_svms[1].name }}"
    enabled:                      true
    protocol:
      v3_enabled:                 true
      v40_enabled:                true
      v41_enabled:                false
      v3_64bit_identifiers_enabled: true
      v4_64bit_identifiers_enabled: true
    showmount_enabled:            true

protocols_active_directory:
  cluster1_ad:
    preferred-domain-controllers:
      - fqdn:                    "demo.netapp.com"
        ip:                      "192.168.0.253"
  ntap-svm01-nas:
    preferred-domain-controllers:
      - fqdn:                    "demo.netapp.com"
        ip:                      "192.168.0.253"

protocols_cifs_services:
  - name:                         "{{ svm_svms[0].name }}"
    svm:
      name:                       "{{ svm_svms[0].name }}"
    ad_domain:
      fqdn:                       "{{ all_ad_domain }}"
      organizational_unit:        "{{ all_storage_ad_ou_path }}"
    comment:                      "This CIFS Server is for cluster AD authentication"
    enabled:                      true
  - name:                         "svm01-nas"
    svm:
      name:                       "{{ svm_svms[1].name }}"
    ad_domain:
      fqdn:                       "{{ all_ad_domain }}"
      organizational_unit:        "{{ all_storage_ad_ou_path }}"
    comment:                      "This CIFS Server is created for the primary NAS SVM"
    enabled:                      true
  - name:                         "svm02-san"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ad_domain:
      fqdn:                       "{{ all_ad_domain }}"
      organizational_unit:        "{{ all_storage_ad_ou_path }}"
    comment:                      "This CIFS Server is created for the primary SAN SVM"
    enabled:                      true

protocols_san_iscsi_services:
  - svm:
      name:                       "{{ svm_svms[2].name }}"
    enabled:                      true

protocols_nvme_services:
  - svm:
      name:                       "{{ svm_svms[2].name }}"
    enabled:                      true

network_ip_interfaces:
  - name:                         "{{ svm_svms[0].name }}"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[0].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.210"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                true
    service_policy:
      name:                       "default-management"
  - name:                         "{{ svm_svms[1].name }}"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[1].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.211"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                true
    service_policy:
      name:                       "default-data-files"
  - name:                         "{{ svm_svms[2].name }}"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.212"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                true
    service_policy:
      name:                       "default-management"
  - name:                         "{{ svm_svms[2].name }}_iscsi01"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.215"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                false
    service_policy:
      name:                       "default-data-blocks"
  - name:                         "{{ svm_svms[2].name }}_iscsi02"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.216"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                false
    service_policy:
      name:                       "default-data-blocks"
  - name:                         "{{ svm_svms[2].name }}_nvme01"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.217"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                false
    service_policy:
      name:                       "default-data-nvme-tcp"
  - name:                         "{{ svm_svms[2].name }}_nvme02"
    scope:                        "svm"
    svm:
      name:                       "{{ svm_svms[2].name }}"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.218"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                false
    service_policy:
      name:                       "default-data-nvme-tcp"
  - name:                         "{{ cluster_nodes[0].name }}_ic01"
    scope:                        "cluster"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.121"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[0].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                true
    service_policy:
      name:                       "default-intercluster"
    ipspace:
      name:                       "Default"
  - name:                         "{{ cluster_nodes[1].name }}_ic01"
    scope:                        "cluster"
    ip:
      netmask:                    "24"
      address:                    "192.168.0.122"
      family:                     "ipv4"
    location:
      home_node:
        name:                     "{{ cluster_nodes[1].name }}"
      home_port:
        name:                     "e0c"
      auto_revert:                true
    service_policy:
      name:                       "default-intercluster"
    ipspace:
      name:                       "Default"

cluster_peers:
  - name:                        "cluster2"
    authentication:
      generate_passphrase:        false
      passphrase:                 "{{ vault_custer_peers.phassphrase }}"
    encryption:
      proposed:                   "tls_psk"
    ipspace: 
      name:                       "Default"
    local_network:
      interfaces:
        - ip_address:             "192.168.0.121"
        - ip_address:             "192.168.0.122"
    remote:
      ip_addresses:
        - "192.168.0.123"
        - "192.168.0.124"