################################################################################
#
# Title:        ONTAP-revert-42 - Quality of Service
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2024-01-19
# Description:  Revert all steps performed in test frame 42
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "linux"
  name:                                "ONTAP-revert-42 - Quality of Service - Linux"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix

  tasks:
    - name: Unmount export
      ansible.posix.mount:
        state:                         "absent"
        src:                           "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/\
                                        {{ item }}/{{ item }}{{ ontap_42_nfs_suffix }}"
        path:                          "{{ linux_42_mount_dir }}/{{ item }}{{ ontap_42_nfs_suffix }}"
#        opts:                          "rw,sync,hard,vers=3"
        fstype:                        "nfs"
      loop:
        - "{{ ontap_42_vol_name }}"
        - "{{ ontap_42_qos_vol_name }}"

    - name: Remove mount directories
      ansible.builtin.file:
        path:                          "{{ linux_42_mount_dir }}/{{ item }}{{ ontap_42_nfs_suffix }}"
        state:                         "absent"
        mode:                          "0755"
      loop:
        - "{{ ontap_42_vol_name }}"
        - "{{ ontap_42_qos_vol_name }}"

    - name: Remove default parent mount directory
      ansible.builtin.file:
        path:                          "{{ linux_42_mount_dir }}"
        state:                         "absent"
        mode:                          "0755"

- hosts:                               "primary_storage_cluster"
  name:                                "ONTAP-revert-42 - Quality of Service - ONTAP"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  tasks:
    - name: Remove CIFS share
      netapp.ontap.na_ontap_cifs:
        state:                         absent
        name:                          "{{ item }}{{ ontap_42_cifs_suffix }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input
      loop:
        - "{{ ontap_42_vol_name }}"
        - "{{ ontap_42_qos_vol_name }}"

    - name: Remove volumes
      netapp.ontap.na_ontap_volume:
        state:                         absent
        name:                          "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input
      loop:
        - "{{ ontap_42_vol_name }}"
        - "{{ ontap_42_qos_vol_name }}"

    - name: Remove read-write export policy
      netapp.ontap.na_ontap_export_policy:
        state:                         absent
        name:                          "{{ ontap_42_policy_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input