################################################################################
#
# Title:        ONTAP-42-01 - QoS Policy
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-19
# Description:  Quality of Service
#               - QoS Policy
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-42-02 - QoS Policy"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create QoS policy
      netapp.ontap.na_ontap_qos_policy_group:
        state:                         present
        name:                          "{{ ontap_42_qos_policy_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        fixed_qos_options:
          max_throughput_iops: 1000
          max_throughput_mbps: 10
          min_throughput_iops: 100
          min_throughput_mbps: 1
          capacity_shared: True
        <<: *input
  post_tasks: