################################################################################
#
# Title:        ONTAP-42-02 - Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-19
# Description:  Quality of Service
#               - Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_cluster"
  name:                                "ONTAP-42-02 - Volumes"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:    
    - name: Create non-QoS volume
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ ontap_42_vol_name }}"
        aggregate_name:                "{{ storage_aggregates[0].name }}"
        size:                          "{{ ontap_default_vol_size_gb }}"
        size_unit:                     gb
        space_guarantee:               none
        tiering_policy:                auto
        export_policy:                 "ro_{{ global_primary_nas_svm }}"
        junction_path:                 "/{{ ontap_42_vol_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume_security_style:         "unix"
        <<: *input

    - name: Create QoS volume
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ ontap_42_qos_vol_name }}"
        aggregate_name:                "{{ storage_aggregates[0].name }}"
        size:                          "{{ ontap_default_vol_size_gb }}"
        size_unit:                     gb
        space_guarantee:               none
        tiering_policy:                auto
        export_policy:                 "ro_{{ global_primary_nas_svm }}"
        junction_path:                 "/{{ ontap_42_qos_vol_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume_security_style:         "unix"
        qos_policy_group:              "{{ ontap_42_qos_policy_name }}"
        <<: *input

  post_tasks: