################################################################################
#
# Title:        init_ad.yml
# Author:       NetApp Inc. (badrian)
# Date:         2020-10-13
# Description:  Configure users and groups in Active Directoy
#
# Collections:  community.windows
#
# URL:          https://galaxy.ansible.com/community/windows
#
################################################################################

- hosts: dc1
  gather_facts: false
  vars:
    separator: '\'
    ad_org_groups:
      - name: "{{ ontap_ad_admin_group.split(separator)[-1] }}"
        users:
          - LoD_Org_Admin_01
          - LoD_Org_Admin_02
          - "{{ ontap_ad_admin_user.split(separator)[-1] }}"
      - name: "{{ ontap_ad_ro_group.split(separator)[-1] }}"
        users:
          - LoD_Org_User_01
          - LoD_Org_User_02
          - "{{ ontap_ad_ro_user.split(separator)[-1] }}"
      - name: "LoD Org Approvers"
        users:
          - LoD_Org_Approver_01
          - LoD_Org_Approver_02
      - name: "LoD Org Auditors"
        users:
          - LoD_Org_Auditor_01
          - LoD_Org_Auditor_02
  vars_files:
    - ../../playbooks/vars/vars_devlab.yml
  collections:
    - community.windows

  tasks:
  - name: Create DNS record for centos1
    community.windows.win_dns_record:
      state:                       "present"
      name:                        "centos1"
      type:                        "A"
      value:                       "192.168.0.61"
      zone:                        "{{ pocenv_secondary_dns_domain }}"

  - name: Create DNS records for test SVMs (first IP of each SVM)
    community.windows.win_dns_record:
      state:                       "present"
      name:                        "{{ item.name }}"
      type:                        "A"
      value:                       "{{ item.lifs[0].ip }}"
      zone:                        "{{ pocenv_secondary_dns_domain }}"
    loop:
      "{{ ontap_svms }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Create DNS record for s3server
    community.windows.win_dns_record:
      state:                       "present"
      name:                        "s3server"
      type:                        "A"
      value:                       "192.168.0.233"
      zone:                        "demo.netapp.com"

  - name: Create OU in Active Directory
    community.windows.win_domain_ou:
      state:                       present
      name:                        "{{ pocenv_default_ad_ou_path.split(',')[0].split('=')[1] }}"
      path:                        "{{ ','.join(pocenv_default_ad_ou_path.split(',')[1:]) }}"

  - name: Create LoD Groups in AD
    community.windows.win_domain_group:
      state:                       present
      name:                        "{{ item.name }}"
      scope:                       "global"
      path:                        "CN=Users,DC=demo,DC=netapp,DC=com"
    loop:
      "{{ ad_org_groups }}"

  - name: Create LoD Users in AD
    community.windows.win_domain_user:
      state:                       present
      name:                        "{{ item.1 }}"
      path:                        "CN=Users,DC=demo,DC=netapp,DC=com"
      password:                    "{{ ontap_ad_admin_pw_setup }}"
      update_password:             "on_create"
      password_never_expires:      "yes"
      user_cannot_change_password: "yes"
      groups:
        - "{{ item.0.name }}"
    with_subelements:
      - "{{ ad_org_groups }}"
      - users
