################################################################################
#
# Title:        init_ad.yml
# Author:       NetApp Inc. (badrian)
# Date:         2020-10-13
# Description:  Configure users and groups in Active Directoy
#
# Collections:  community.windows
#
# URL:          https://galaxy.ansible.com/community/windows
#
################################################################################

- hosts:                               "windows_domain_controllers"
  name:                                "Initialize Lab DC"
  gather_facts:                        false
  vars:
    separator: '\'
    ad_org_groups:
      - name:         "{{ ontap_12_ad_ro_group.split(separator)[-1] }}"
        users:
          - name:     "{{ ontap_12_ad_ro_user.split(separator)[-1] }}"
            password: "{{ ontap_12_ad_ro_user_pw }}"
      - name:         "{{ ontap_12_ad_admin_group.split(separator)[-1] }}"
        users:
          - name:     "{{ ontap_12_ad_admin_user.split(separator)[-1] }}"
            password: "{{ ontap_12_ad_admin_user_pw }}"
      - name:         "bluecorp"
        users:        
          - name:     "{{ ontap_82_bluecorp_user.split(separator)[-1]  }}"
            password: "{{ ontap_82_bluecorp_user_pw }}"
      - name:         "astrainc"
        users:
          - name:     "{{ ontap_82_astrainc_user.split(separator)[-1]  }}"
            password: "{{ ontap_82_astrainc_user_pw }}"
      - name:         "polarisltd"
        users:
          - name:     "{{ ontap_82_polarisltd_user.split(separator)[-1]  }}"
            password: "{{ ontap_82_polarisltd_user_pw }}"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - community.windows
    - microsoft.ad

  tasks:
    - name: Create DNS record for linux system
      community.windows.win_dns_record:
        state:                         "present"
        name:                          "{{ item }}"
        type:                          "A"
        value:                         "192.168.0.61"
        zone:                          "{{ all_default_dns_domain }}"
      loop:
        - "{{ groups['linux_hosts'][0] }}"
        - "self-service"

    - name: Create DNS records for SVM interfaces (DNS name = interace name)
      community.windows.win_dns_record:
        state:                         "present"
        name:                          "{{ item.name }}"
        type:                          "A"
        value:                         "{{ item.ip.address }}"
        zone:                          "{{ all_default_dns_domain }}"
      when:
        - item.scope == "svm"
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].network_ip_interfaces | list + 
            hostvars[groups['secondary_storage_clusters'][0]].network_ip_interfaces | list }}"
      loop_control:
        label: "{{ item.name }}"
  
    - name: Create DNS record for s3server
      community.windows.win_dns_record:
        state:                         "present"
        name:                          "s3server"
        type:                          "A"
        value:                         "192.168.0.233"
        zone:                          "{{ all_default_dns_domain }}"
  
    - name: Create OU in Active Directory
      microsoft.ad.ou:
        state:                         present
        name:                          "{{ all_storage_ad_ou_path.split(',')[0].split('=')[1] }}"
        path:                          "{{ ','.join(all_storage_ad_ou_path.split(',')[1:]) }}"
  
    - name: Create LoD Groups in AD
      microsoft.ad.group:
        state:                         present
        name:                          "{{ item.name }}"
        scope:                         "global"
        path:                          "CN=Users,DC=demo,DC=netapp,DC=com"
      loop:
        "{{ ad_org_groups }}"
  
    - name: Create LoD Users in AD
      microsoft.ad.user:
        state:                         present
        name:                          "{{ item.1.name }}"
        path:                          "CN=Users,DC=demo,DC=netapp,DC=com"
        password:                      "{{ item.1.password }}"
        update_password:               "always"
        password_never_expires:        "yes"
        user_cannot_change_password:   "yes"
        groups:
          add:
            - "{{ item.0.name }}"
      with_subelements:
        - "{{ ad_org_groups }}"
        - users
