################################################################################
#
# Title:        init_ontap.yml
# Author:       NetApp Inc. (badrian)
# Date:         2023-07-31
# Description:  Prepare lab system
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_aggregate
# ansible-doc netapp.ontap.na_ontap_rest_info
#
################################################################################

- hosts:              "ontap"
  name:               "Initialize ONTAP clusters"
  gather_facts:       false
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "Always"
  vars_files:
    - ../../playbooks/vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Get all volumes from clusters
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
      - "storage/volumes"
      fields:
      - "svm"
      use_python_keys:            true
      hostname:                   "{{ ansible_host }}"
      <<: *input
    register: vol_info

  - name: Move volumes to standard test aggregate
    netapp.ontap.na_ontap_volume:
      state:                      absent
      name:                       "{{ item.name }}"
      vserver:                    "{{ item.svm.name }}"
      wait_for_completion:        true
      hostname:                   "{{ ansible_host }}"
      <<: *input
    when:
    - vol_info.ontap_info['storage/volumes'].num_records|int > 0
    - item.name is defined
    loop:
      "{{ vol_info.ontap_info.storage_volumes.records }}"

#  - name: Delete non-standard aggregate
#    netapp.ontap.na_ontap_aggregate:
#      state:                      absent
#      name:                       "{{ ontap_primary_cluster_aggr02 }}"
#      hostname:                   "{{ ontap_hostname }}"
#      <<: *input