# Ansible Variables

# Custom Variables
all_default_gateway:          "192.168.0.1"
all_default_dns_domain:       "demo.netapp.com"
all_ad_domain:                "{{ all_default_dns_domain }}"
all_storage_ad_ou_path:       "OU=Storage,DC=DEMO,DC=NETAPP,DC=COM"
all_dns_domains:
- "{{ all_default_dns_domain }}"
all_dns_nameservers:
- "192.168.0.253"
all_ntp_serveres:
- "0.us.pool.ntp.org"
- "1.us.pool.ntp.org"
all_timezone:                 "America/New_York"

all_ad_join_user:             "{{ vault_all_ad_join_user }}"
all_ad_join_password:         "{{ vault_all_ad_join_password }}"