################################################################################
#
# Title:        ONTAP-52-11 - Bulk Protect Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Bulk Protect Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-52-11 - Bulk Protect Volumes - ONTAP Primary"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Get all volumes to be protected
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "storage/volumes"
        fields:
          - "svm"
        parameters:
          is_svm_root:                 false
          svm.name:                    "{{ global_primary_nas_svm }}|{{ global_primary_san_svm }}"
        use_python_keys:               true
      register: vol_info
  
  post_tasks:

- hosts:                               "secondary_storage_clusters"
  name:                                "ONTAP-52-11 - Protect Volumes - ONTAP Secondary"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create backup volumes
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records }}"
      loop_control:
        label: "{{ item.svm.name + ':' + item.name }}"
      when:
        - hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records | length > 0
        - item.name is defined
        - item.svm.name is defined

    - name: Setup volume protection
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.svm.name + ':' + item.name }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + item.name + '_dst' }}"
        create_destination:
          enabled:                     true
        update:                        false
        initialize:                    false
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records }}"
      loop_control:
        label: "{{ item.svm.name + ':' + item.name }}"
      when:
        - hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records | length > 0
        - item.name is defined
        - item.svm.name is defined

    - name: Initialize all
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.svm.name + ':' + item.name }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + item.name + '_dst' }}"
        update:                        false
        initialize:                    true
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records }}"
      loop_control:
        label: "{{ item.svm.name + ':' + item.name }}"
      when:
        - hostvars[groups['primary_storage_clusters'][0]].vol_info.ontap_info.storage_volumes.records | length > 0
        - item.name is defined
        - item.svm.name is defined

  post_tasks: