################################################################################
#
# Title:        ONTAP-52-09 - Restore Backup
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Restore Backup
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-52-09 - Restore Backup"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Restore files from backup
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        relationship_type:             "restore"
        destination_endpoint:
          cluster:                     "{{ hostvars[gropus['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_nas_svm + ':' + ontap_52_vol_name }}"
        source_endpoint:
          cluster:                     "{{ hostvars['secondary_storage_cluster'].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        source_snapshot:               "{{ ontap_52_snapshot_name }}"
        <<: *input

  post_tasks: