################################################################################
#
# Title:        ONTAP-52-07 - Incremental Backup
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Incremental Backup
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-52-07 - Incremental Backup - ONTAP Primary"
  gather_facts:                        false
  vars:
    input_01: &input_01
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create snapshot with SnapMirror label
      netapp.ontap.na_ontap_snapshot:
        state:                         present
        snapshot:                      "{{ ontap_52_snapshot_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume:                        "{{ ontap_52_vol_name }}"
        snapmirror_label:              "{{ ontap_52_snapm_adhoc_label }}"
        comment:                       "ONTAP Test 52"
        <<: *input_01

  post_tasks:

- hosts:                               "secondary_storage_clusters"
  name:                                "ONTAP-52-07 - Incremental Backup - ONTAP Secondary"
  gather_facts:                        false
  vars:
    input_02: &input_02
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Update SnapMirror relation
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[gropus['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_nas_svm + ':' + ontap_52_vol_name }}"
        destination_endpoint:
          cluster:                     "{{ hostvars['secondary_storage_cluster'].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        update:                        true
        <<: *input_02

  post_tasks: