################################################################################
#
# Title:        ONTAP-52-01 - SVM Peering
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - SVM Peering
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-52-01 - SVM Peering"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create SVM Peerings
      netapp.ontap.na_ontap_vserver_peer:
        state:                         present
        vserver:                       "{{ item }}"
        peer_vserver:                  "{{ global_primary_backup_svm }}"
        peer_cluster:                  "{{ global_secondary_test_cluster }}"
        applications:
          - "snapmirror"
        peer_options:
          hostname: "{{ global_secondary_test_cluster }}"
        <<: *input
      loop:
        - "{{ global_primary_nas_svm }}"
        - "{{ global_primary_san_svm }}"

  post_tasks: