################################################################################
#
# Title:        ONTAP-52-04 - Protect Volume
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Protect Volume
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "secondary_storage_clusters"
  name:                                "ONTAP-52-04 - Protect Volume"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Setup volume protection
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_nas_svm + ':' + ontap_52_vol_name }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        create_destination:
          enabled:                     true
        policy:                        "{{ ontap_52_snapm_policy_name }}"
        schedule:                      "5min"
        update:                        false
        initialize:                    false

    - name: Initialize backup
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_nas_svm + ':' + ontap_52_vol_name }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        update:                        false
        initialize:                    true

  post_tasks: