################################################################################
#
# Title:        ONTAP-52-06 - Additional Files
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Additional Files
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "linux"
  name:               "ONTAP-52-06 - Additional Files - Linux"
  gather_facts:       false
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:

  tasks:
    - name: Create additional test files
      community.general.filesize:
        path: "{{ linux_52_mount_dir }}/{{ ontap_52_lin_qtree_name }}/{{ item }}"
        size: 50MB
      loop:
        - "testfile_11"
        - "testfile_12"
        - "testfile_13"
  
  post_tasks:

- hosts:              "win_hosts"
  name:               "ONTAP-52-06 - Additional Files - Windows"
  gather_facts:       false
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Create additional test files
      ansible.windows.win_file:
        path:                     "\\\\{{ global_primary_nas_svm }}\\{{ ontap_52_win_qtree_name}}\\{{ item }}"
        state:                    touch
      loop:
        - "testfile_11"
        - "testfile_12"
        - "testfile_13"
      vars:
        ansible_become:           "yes"
        ansible_become_method:    "runas"
        ansible_become_user:      "{{ ansible_user }}"
        ansible_become_pass:      "{{ ansible_password }}"

  post_tasks: