################################################################################
#
# Title:        ONTAP-52-04 - Create Backup Relation
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Create Backup Relation
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_secondary_test_cluster }}"
  name:               "ONTAP-52-04 - Create Backup Relation"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Setup volume protection
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ global_primary_test_cluster }}"
          path:                        "{{ item.svm.name + ':' + ontap_52_vol_name }}"
        destination_endpoint:
          cluster:                     "{{ global_secondary_test_cluster }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        create_destination:
          enabled:                     true
        update:                        false
        initialize:                    false
        <<: *input

    - name: Initialize backup
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ global_primary_test_cluster }}"
          path:                        "{{ global_primary_test_cluster + ':' + ontap_52_vol_name }}"
        destination_endpoint:
          cluster:                     "{{ global_secondary_test_cluster }}"
          path:                        "{{ global_primary_backup_svm + ':' + ontap_52_vol_name + '_dst' }}"
        update:                        false
        initialize:                    true
        <<: *input

  post_tasks: