################################################################################
#
# Title:        ONTAP-52-02 - Volume Protection
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Backup (SnapMirror)
#               - Volume Protection
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_secondary_test_cluster }}"
  name:               "ONTAP-52-02 - Volume Protection"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Get all volumes to be protected
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "storage/volumes"
        fields:
          - "svm"
        parameters:
          is_svm_root:                 false
          svm.name:                    "{{ global_primary_nas_svm }}|{{ global_primary_san_svm }}"
        use_python_keys:               true
        <<: *input
      register: vol_info
  
    - name: Protect all volumes  
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ global_primary_test_cluster }}"
          path:                        "{{ item.svm.name + ':' + item.name }}"
        destination_endpoint:
          cluster:                     "{{ global_secondary_test_cluster }}"
          path:                        "{{ global_primary_backup_svm + ':' + item.name + '_dst' }}"
        create_destination:
          enabled: true
        <<: *input
      loop:
        "{{ vol_info.ontap_info.storage_volumes.records }}"
      loop_control:
        label: "{{ item.svm.name + ':' + item.name }}"
      when:
        - vol_info.ontap_info.storage_volumes.records | length > 0
        - item.name is defined
        - item.svm.name is defined
  
  post_tasks: