################################################################################
#
# Title:        ONTAP-35-03 - LUNs & Mappings
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - LUNs & Mappings
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-35-03 - LUNs & Mappings"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create LUNs - Unified ONTAP
      netapp.ontap.na_ontap_lun:
        state:                         present
        vserver:                       "{{ global_primary_san_svm }}"
        name:                          "{{ (item | split('/'))[3] }}"
        flexvol_name:                  "{{ (item | split('/'))[2] }}"
        size:                          "{{ ontap_default_lun_size_gb }}"
        size_unit:                     "gb"
        os_type:                       "{{ 'linux' if 'lin' in (item | split('/'))[3] else
                                           'windows' if 'win' in (item | split('/'))[3] else
                                           default(omit) }}"
        space_reserve:                 true
        space_allocation:              true
      loop:
        "{{ ontap_35_lin_luns +
            ontap_35_win_luns }}"
      when:
        - not cluster.disaggregated

    - name: Map LUNs to iGroups
      netapp.ontap.na_ontap_lun_map:
        state:                         present
        vserver:                       "{{ global_primary_san_svm }}"
        initiator_group_name:          "{{ ontap_35_lin_igroup_name if 'lin' in (item | split('/'))[3] else
                                           ontap_35_win_igroup_name if 'win' in (item | split('/'))[3] else
                                           default(omit) }}"
        path:                          "{{ item }}"
      loop:
        "{{ ontap_35_lin_luns +
            ontap_35_win_luns }}"
      when:
        - not cluster.disaggregated

    - name: Create LUNs - ASAr2
      netapp.ontap.na_ontap_restit:
        api:                           'storage/luns'
        method:                        'POST'
        body:
          svm:
            name:                      "{{ global_primary_san_svm }}"
          name:                        "{{ (item | split('/'))[-1] }}"
          os_type:                     "{{ 'linux' if 'lin' in (item | split('/'))[-1] else
                                           'windows' if 'win' in (item | split('/'))[-1] else
                                           default(omit) }}"
          space:
            size:                       "{{ ontap_default_lun_size_gb * 1024 * 1024 * 1024 }}"
          lun_maps:
            - igroup:
                name:                   "{{ ontap_35_lin_igroup_name if 'lin' in (item | split('/'))[-1] else
                                            ontap_35_win_igroup_name if 'win' in (item | split('/'))[-1] else
                                            default(omit) }}"
      loop:
        "{{ ontap_35_lin_luns +
            ontap_35_win_luns }}"
      when:
        - cluster.disaggregated

  post_tasks: