################################################################################
#
# Title:        ONTAP-35-04 - Mount & Write (Linux)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - Mount & Write (Linux)
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-35-04 - Mount & Write (Linux) - ONTAP"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Get iSCSI target info from "{{ global_primary_san_svm }}" 
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "protocols/san/iscsi/services"
        fields:
          - "svm"
          - "target"
        parameters:
          svm.name:                    "{{ global_primary_san_svm }}"
        use_python_keys:               true
      register: iscsi_info
    
    - name: Get LUNs from "{{ global_primary_san_svm }}"
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "storage/luns"
        fields:
          - "svm"
          - "location"
          - "serial_number"
        parameters:
          svm.name:                    "{{ global_primary_san_svm }}"
        use_python_keys:               true
      register: lun_info

  post_tasks:

- hosts:                               "linux_hosts"
  name:                                "ONTAP-35-04 - Mount & Write (Linux) - Linux"
  gather_facts:                        true
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - community.general
    - ansible.posix

  pre_tasks:

  tasks:
    - name: Discover iSCSI targets on SVM and login
      community.general.open_iscsi:
        show_nodes:                    true
        discover:                      true
        login:                         true
        auto_portal_startup:           true
        auto_node_startup:             true
        portal:                        "{{ item.ip.address }}"
        target:                        "{{ (hostvars[groups['primary_storage_clusters'][0]].iscsi_info.ontap_info.protocols_san_iscsi_services.records |
                                            first ).target.name }}"
      loop_control:
        label: "{{ item.ip.address }}"
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].network_ip_interfaces |
            selectattr('svm.name', 'defined') |
            selectattr('svm.name', '==', global_primary_san_svm) |
            selectattr('service_policy.name', 'search', 'block') |
            list }}"

    - name: Build Filesystem on new LUN
      community.general.filesystem:
        fstype:                        "ext4"
        dev:                           "/dev/mapper/{{ ontap_iscsi_vendor_id }}\
                                        {{ (hostvars[groups['primary_storage_clusters'][0]].lun_info.ontap_info.storage_luns.records |
                                           selectattr('name', 'defined') |
                                           selectattr('name', '==', item ) |
                                           first ).serial_hex }}"
      loop:
        "{{ ontap_35_lin_luns }}"

    - name: Create mount directory  
      ansible.builtin.file:
        path:                          "{{ linux_35_mount_dir }}/{{ item | split('/') | last }}"
        state:                         "directory"
        mode:                          "0755"
      loop:
        "{{ ontap_35_lin_luns }}"

    - name: Mount LUN
      ansible.posix.mount:
        state:                         "mounted"
        src:                           "/dev/mapper/{{ ontap_iscsi_vendor_id }}\
                                        {{ (hostvars[groups['primary_storage_clusters'][0]].lun_info.ontap_info.storage_luns.records |
                                           selectattr('name', 'defined') |
                                           selectattr('name', '==', item ) |
                                           first ).serial_hex }}"
        path:                          "{{ linux_35_mount_dir }}/{{ item | split('/') | last }}"
        fstype:                        "ext4"
        opts:                          "discard"
      loop:
        "{{ ontap_35_lin_luns }}"

    - name: Create test file on LUN
      community.general.filesize:
        path: "{{ linux_35_mount_dir }}/{{ item | split('/') | last }}/{{ item | split('/') | last }}_testfile"
        size: 50MB
      loop:
        "{{ ontap_35_lin_luns }}"

  post_tasks: