################################################################################
#
# Title:        ONTAP-35-03 - LUNs & Mappings
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - LUNs & Mappings
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-35-03 - LUNs & Mappings"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../../vars/labondemand/vars.yml
    - ../../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create LUNs
      netapp.ontap.na_ontap_lun:
        state:                    present
        vserver:                  "{{ global_primary_san_svm }}"
        name:                     "{{ (item | split('/'))[3] }}"
        flexvol_name:             "{{ (item | split('/'))[2] }}"
        size:                     "{{ ontap_default_lun_size_gb }}"
        size_unit:                "gb"
        os_type:                  "{{ 'linux' if 'lin' in (item | split('/'))[3] else
                                      'windows' if 'win' in (item | split('/'))[3] else
                                      default(omit) }}"
        space_reserve:            true
        space_allocation:         true
        <<: *input
      loop:
        "{{ ontap_35_lin_luns +
            ontap_35_win_luns }}"

    - name: Map LUNs to iGroups
      netapp.ontap.na_ontap_lun_map:
        state:                    present
        vserver:                  "{{ global_primary_san_svm }}"
        initiator_group_name:     "{{ ontap_35_lin_igroup_name if 'lin' in (item | split('/'))[3] else
                                      ontap_35_win_igroup_name if 'win' in (item | split('/'))[3] else
                                      default(omit) }}"
        path:                     "{{ item }}"
        <<: *input
      loop:
        "{{ ontap_35_lin_luns +
            ontap_35_win_luns }}"

  post_tasks: