################################################################################
#
# Title:        ONTAP-35-01 - iGroups
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - iGroups
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-35-01 - iGroups"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create a iGroups
      netapp.ontap.na_ontap_igroup:
        state:                         present
        vserver:                       "{{ global_primary_san_svm }}"
        name:                          "{{ item }}"
        initiator_group_type:          "iscsi"
        os_type:                       "{{ 'linux' if 'lin' in item else
                                           'windows' if 'win' in item else
                                           default(omit) }}"
        initiator_names:               "{{ ontap_35_lin_igroup_iqns if 'lin' in item else
                                           ontap_35_win_igroup_iqns if 'win' in item else
                                           default(omit) }}"
      loop:
        - "{{ ontap_35_lin_igroup_name }}"
        - "{{ ontap_35_win_igroup_name }}"

  post_tasks: