################################################################################
#
# Title:        ONTAP-prepare-20 - Storage Virtual Machines (SVMs)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-01-08
# Description:  Execute all pre-steps for running test frame 20
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-10-01.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-10-02.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-10-03.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-10-04.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-10-05.yml

- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-11-01.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-11-02.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-11-03.yml

- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-12-01.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-12-02.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-12-04.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-12-05.yml
- ansible.builtin.import_playbook: ../ONTAP-10/ONTAP-12-10.yml