################################################################################
#
# Title:        ONTAP-81-01 - Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-02-09
# Description:  Advanced - CIFS Self-Service
#               - Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-81-01 - Volumes"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create volume
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ item }}"
        aggregate_name:                "{{ storage_aggregates[0].name }}"
        size:                          "{{ ontap_default_vol_size_gb }}"
        size_unit:                     gb
        space_guarantee:               none
        tiering_policy:                auto
        junction_path:                 "/{{ ontap_32_vol_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume_security_style:         "ntfs"
        <<: *input
      loop:
        "{{ ontap_81_volumes }}""
  
  post_tasks: