################################################################################
#
# Title:        ONTAP-revert-81 - Advanced - CIFS Self-Service
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-02-09
# Description:  Revert all steps performed in test frame 81
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-revert-81 - Advanced - CIFS Self-Service"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Remove volume
      netapp.ontap.na_ontap_volume:
        state:                         absent
        name:                          "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input
      loop:
        "{{ ontap_81_volumes }}"

  post_tasks: