################################################################################
#
# Title:        ONTAP-81-21 - Backup Demo Roll-out
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2025-02-19
# Description:  Advanced - Self-service
#               - Backup Demo Roll-out
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "secondary_storage_clusters"
  name:                                "ONTAP-81-21 - Backup Demo Roll-out"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Setup volume protection
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.0 + ':' + item.1 }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.0 + '-backup:' + item.1 + '_dst' }}"
        create_destination:
          enabled:                     true
        policy:                        "{{ ontap_81_snapm_policy_standard }}"
        schedule:                      "10min"
        update:                        false
        initialize:                    false
      loop:
        "{{ ontap_81_svms | product(ontap_81_volumes[:2]) | list }}"

    - name: Initialize backup
      netapp.ontap.na_ontap_snapmirror:
        state:                         present
        source_endpoint:
          cluster:                     "{{ hostvars[groups['primary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.0 + ':' + item.1 }}"
        destination_endpoint:
          cluster:                     "{{ hostvars[groups['secondary_storage_clusters'][0]].cluster.name }}"
          path:                        "{{ item.0 + '-backup:' + item.1 + '_dst' }}"
        update:                        false
        initialize:                    true
      loop:
        "{{ ontap_81_svms | product(ontap_81_volumes[:2]) | list }}"

  post_tasks: