################################################################################
#
# Title:        ONTAP-prepare-81 - Advanced - Self-service
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-02-09
# Description:  Execute all pre-steps for running test frame 81
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- ansible.builtin.import_playbook: ../ONTAP-20/ONTAP-prepare-20.yml

- ansible.builtin.import_playbook: ../ONTAP-15/ONTAP-15-01.yml
- ansible.builtin.import_playbook: ../ONTAP-15/ONTAP-15-02.yml