################################################################################
#
# Title:        ONTAP-81-01 - Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-02-09
# Description:  Advanced - Service Provider Customization
#               - Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-81-01 - Volumes"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create volume
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ item.1 }}"
        aggregate_name:                "{{ storage_aggregates[0].name }}"
        size:                          1024
        size_unit:                     gb
        space_guarantee:               none
        tiering_policy:                auto
        junction_path:                 "/{{ item.1 }}"
        vserver:                       "{{ item.0 }}"
        volume_security_style:         "ntfs"
      loop:
        "{{ ontap_80_svms | product(ontap_80_volumes) | list }}"
  
    - name: Set default quota rule on volumes
      netapp.ontap.na_ontap_quotas:
        state:                         present
        vserver:                       "{{ item.0 }}"
        volume:                        "{{ item.1 }}"
        quota_target:                  ""
        type:                          tree
        set_quota_status:              True
      loop:
        "{{ ontap_80_svms | product(ontap_80_volumes) | list }}"

  post_tasks: