################################################################################
#
# Title:        ONTAP-revert-00 - Return to Day0 - Windows
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Revert all systems to initial state
#               - Windows
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "win_hosts"
  name:                                "ONTAP-revert-00 - Return to Day0 - Windows"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Read iSCSI targets
      ansible.windows.win_powershell:
        script: 
          "Get-IscsiTarget"
      register: ps_iscsi_targets

    - name: Disconnect iSCSI targets
      ansible.windows.win_powershell:
        script:
          "Disconnect-IscsiTarget \
           -NodeAddress {{ (ps_iscsi_targets.output | \
                            selectattr('NodeAddress', 'search', 'netapp') | \
                            first).NodeAddress }} \
           -Confirm:$false"
      when:
        - ps_iscsi_targets.output | length > 0

    - name: Remove iSCSI portals
      ansible.windows.win_powershell:
        script:
          "Remove-IscsiTargetPortal \
           -TargetPortalAddress {{ item.ip.address }} \
           -Confirm:$false"
      loop_control:
        label: "{{ item.ip.address }}"
      loop:
        "{{ hostvars[groups['primary_storage_clusters'][0]].network_ip_interfaces |
            selectattr('svm.name', 'defined') |
            selectattr('svm.name', '==', global_primary_san_svm) |
            selectattr('service_policy.name', 'search', 'block') |
            list }}"

    - name: Remove root mount directory
      ansible.windows.win_file:
        path:                          "{{ windows_35_mount_dir }}"
        state:                         absent

    - name: 
      block:
        - name: Remove mapped shares
          community.windows.win_shortcut:
            state:                     absent
            dest:                      "{{ windows_32_mount_dir }}\\{{ item }}.lnk"
          loop:
            "{{ ontap_32_vol_qtree_names +
                ontap_32_fg_qtree_names }}"

        - name: Remove network credentials
          community.windows.win_credential:
            state:                     absent
            name:                      "{{ global_primary_nas_svm }}"
            type:                      "domain_password"
      vars:
        # become is required to save and retrieve the credentials in the tasks
        ansible_become:                "yes"
        ansible_become_method:         "runas"
        ansible_become_user:           "{{ ansible_user }}"
        ansible_become_pass:           "{{ ansible_password }}"

    - name: Remove mount directory
      ansible.windows.win_file:
        path:                          "{{ windows_default_mount_dir }}"
        state:                         absent