################################################################################
#
# Title:        BSS-03-13.yml
# Author:       NetApp Inc. (badrian)
# Date:         2023-08-01
# Description:  Move volume to another aggregate
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
#
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               BSS-03-13
  gather_facts:       false
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Move volume from secondary to primary aggregate
    netapp.ontap.na_ontap_volume:
      name:                       "{{ ontap_03_volume_name }}"
      vserver:                    "{{ ontap_primary_nas_svm }}"
      aggregate_name:             "{{ ontap_primary_cluster_aggr01 }}"
      wait_for_completion:        true
      check_interval:             10
      hostname:                   "{{ ontap_hostname }}"
      <<: *input