################################################################################
#
# Title:        BSS-10-03.yml
# Author:       NetApp. Inc (badrian)
# Date:         2023-08-02
# Description:  Create a volume (FlexGroup)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume 
#
################################################################################

- hosts:              "{{ ontap_primary_cluster }}"
  name:               BSS-10-03
  gather_facts:       false
  vars:
    input_01: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - vars/vars_labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: pre_ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ pre_ontap_vols.ontap_info.storage_volumes.records }}"

  tasks:
  - name: Create "mixed" FlexGroup
    netapp.ontap.na_ontap_volume:
      state:                      present
      name:                       "{{ ontap_10_mixed_vol_name }}"
      size:                       "{{ ontap_default_fg_size_gb }}"
      volume_security_style:      "unix"
      aggr_list:
      - "{{ ontap_primary_cluster_aggr01 }}"
      - "{{ ontap_primary_cluster_aggr02 }}"
      aggr_list_multiplier:       "{{ ontap_default_fg_multiplier }}"
      size_unit:                  gb
      space_guarantee:            "none"
      tiering_policy:             "auto"
      export_policy:              "{{ ontap_10_policy_name }}"
      junction_path:              "/{{ ontap_10_mixed_vol_name }}"
      vserver:                    "{{ ontap_secondary_nas_svm }}"
      wait_for_completion:        True
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  - name: Create a test share
    netapp.ontap.na_ontap_cifs:
      state:                      present
      name:                       "{{ ontap_10_mixed_share_name }}"
      path:                       "/{{ ontap_10_mixed_vol_name }}"
      vserver:                    "{{ ontap_secondary_nas_svm }}"
      browsable:                  true
      oplocks:                    true
      show_snapshot:              true
      show_previous_versions:     true
      hostname:                   "{{ ontap_hostname }}"
      <<: *input

  post_tasks:
  - name: Get all volumes
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      fields:
        - name
        - nas
      parameters:
        name: "!vol0,!*_root"
      use_python_keys:          true
      hostname:                 "{{ ontap_hostname }}"
      <<: *input
    register: ontap_vols

  - name: Show all volumes
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ontap_vols.ontap_info.storage_volumes.records }}"
