################################################################################
#
# Title:        ONTAP-revert-00 - Return to Day0 - Linux
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Revert all systems to initial state
#               - Linux
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:              "linux"
  name:               "ONTAP-revert-00 - Return to Day0 - Linux"
  gather_facts:       false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.posix

  tasks:
    - name: Unmount LUNs
      ansible.posix.mount:
        state:                      "absent"
        path:                       "{{ linux_35_default_mount_dir }}/{{ item | split('/') | last }}"
      loop:
        "{{ ontap_35_lin_luns }}"

    - name: Remove default LUN mount directory
      ansible.builtin.file:
        path:                       "{{ linux_35_default_mount_dir }}"
        state:                      "absent"

    - name: List iSCSI targets
      community.general.open_iscsi:
        show_nodes:               true
      register: iscsi_nodes

    - name: Remove iSCSI sessions and logout
      community.general.open_iscsi:
        show_nodes:               false
        discover:                 false
        login:                    false
        auto_portal_startup:      false
        auto_node_startup:        false
        portal:                   "{{ item.ip.address }}"
      loop_control:
        label: "{{ item.ip.address }}"
      loop:
        "{{ hostvars[global_primary_test_cluster].network_ip_interfaces |
            selectattr('svm.name', 'defined') |
            selectattr('svm.name', '==', global_primary_san_svm) |
            selectattr('service_policy.name', 'search', 'block') |
            list }}"
      when:
        - iscsi_nodes.nodes | length > 0

    - name: Remove iSCSI targets
      ansible.builtin.command:
        cmd: "iscsiadm -m node -o delete -T {{ item }}"
      loop:
        "{{ iscsi_nodes.nodes | unique }}"
      when:
        - iscsi_nodes.nodes | length > 0

    - name: Unmount exports
      ansible.posix.mount:
        state:                    "absent"
        src:                      "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/{{ item }}"
        path:                     "{{ linux_default_mount_dir }}/{{ item }}"
        # opts:                     "rw,sync,hard,vers=3"
        fstype:                   "nfs"
      loop:
        - "{{ ontap_31_vol_qtree_names + 
            ontap_31_fg_qtree_names }}"
        - "{{ ontap_41_vol_name }}"
        - "{{ ontap_41_clone_dir_name }}/{{ ontap_41_clone_vol_name }}"
  
    - name: Remove mount directories
      ansible.builtin.file:
        path:                     "{{ linux_default_mount_dir }}/{{ item }}"
        state:                    "absent"
        mode:                     "0755"
      loop:
        - "{{ ontap_31_vol_qtree_names + 
            ontap_31_fg_qtree_names }}"
        - "{{ ontap_41_vol_name }}"
        - "{{ ontap_41_clone_dir_name }}/{{ ontap_41_clone_vol_name }}"
        - "{{ ontap_41_clone_dir_name }}"