################################################################################
#
# Title:        ONTAP-revert-37 - NVMe/TCP
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-11-22
# Description:  Revert all steps performed in test frame 37
#               - NVMe/TCP
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-revert-37 - NVMe/TCP - ONTAP (read)"
  gather_facts:                   false
  vars:
    input_read: &input_read
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Get LUNs from "{{ global_primary_san_svm }}"
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "storage/luns"
        fields:
          - "svm"
          - "location"
          - "serial_number"
        parameters:
          svm.name:               "{{ global_primary_san_svm }}"
        use_python_keys:          true
        <<: *input_read
      register: lun_info

  post_tasks:

- hosts:                          "{{ global_primary_linux_host }}"
  name:                           "ONTAP-revert-37 - NVMe/TCP - Linux"
  gather_facts:                   false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.posix

  pre_tasks:

  tasks:
    - name: Unmount Namespaces
      ansible.posix.mount:
        state:                      "absent"
        path:                       "{{ linux_37_default_mount_dir }}/{{ item | split('/') | last }}"
      loop:
        "{{ ontap_37_lin_namespaces }}"
  
    - name: Remove default Namespace mount directory
      ansible.builtin.file:
        path:                       "{{ linux_37_default_mount_dir }}"
        state:                      "absent"

    - name: Remove iSCSI targets
      ansible.builtin.command:
        cmd: "iscsiadm -m node -o delete -T {{ item }}"
      loop:
        "{{ iscsi_nodes.nodes | unique }}"
      when:
        - iscsi_nodes.nodes | length > 0

    - name: Flush multipath devices
      ansible.builtin.command:
        cmd: "multipath -f {{ ontap_iscsi_vendor_id }}\
                           {{ (hostvars[global_primary_test_cluster].lun_info.ontap_info.storage_luns.records |
                              selectattr('name', 'defined') |
                              selectattr('name', '==', item ) |
                              first ).serial_hex }}"
      when:
        - (hostvars[global_primary_test_cluster].lun_info.ontap_info.storage_luns.records |
           selectattr('name', 'defined') |
           selectattr('name', '==', item ) |
           first ).serial_hex is defined
      loop_control:
        label: "{{ item }} --> \
                {{ ontap_iscsi_vendor_id }}\
                {{ (hostvars[global_primary_test_cluster].lun_info.ontap_info.storage_luns.records |
                    selectattr('name', 'defined') |
                    selectattr('name', '==', item ) |
                    first ).serial_hex }}"
      loop:
        "{{ ontap_35_lin_luns }}"

  post_tasks: