################################################################################
#
# Title:        ONTAP-04-02 - Local admin user
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Cluster User Management
#               - Local admin user
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "ontap"
  name:               "ONTAP-04-02 - Local admin user"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
  - name: Create local user with admin privileges
    netapp.ontap.na_ontap_user:
      state:                      present
      name:                       "{{ ontap_local_admin_user }}"
      applications:               ssh,http,ontapi
      authentication_method:      password
      set_password:               "{{ ontap_local_admin_pw }}"
      lock_user:                  False
      role_name:                  admin
      <<: *input

  post_tasks: