################################################################################
#
# Title:        ONTAP-02-03 - Network services 
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Basic Cluster Configuration
#               - Network services
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "ontap"
  name:               "ONTAP-02-03 - Network services"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/*
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
  - name: Create DNS config on storage cluster
    netapp.ontap.na_ontap_dns:
      state:                      present
      vserver:                    "{{ inventory_hostname }}"
      domains:                    "{{ testenv_dns_domains }}"
      nameservers:                "{{ testenv_dns_nameservers }}"
      use_rest:                   "never"
      <<: *input

  - name: Create NTP server on storage cluster
    netapp.ontap.na_ontap_ntp:
      state:                      present
      server_name:                "{{ item }}"
      version:                    "auto"
      <<: *input
    loop:
      "{{ testenv_ntp_serveres }}"
    retries: 5
    delay: 3
    register: result
    until: not result.failed

  post_tasks: