################################################################################
#
# Title:        ONTAP-02-05 - AutoSupport 
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Basic Cluster Configuration
#               - AutoSupport
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "ontap"
  name:               "ONTAP-02-05 - AutoSupport"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
  - name: Send Test AutoSupport (Call Home)
    netapp.ontap.na_ontap_autosupport_invoke:
      autosupport_message:        "Invoked test autosupport as part of PoC test plan"
      type:                       "test"
      <<: *input

  post_tasks: