################################################################################
#
# Title:        ONTAP-35-05 - Discover, Login & Mount (Windows)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-31
# Description:  iSCSI
#               - Discover, Login & Mount (Windows)
#
# https://www.itprotoday.com/cloud-computing/q-how-can-i-use-command-line-configure-iscsi-connections
# https://www.windowspro.de/wolfgang-sommergut/iscsi-verbindungen-powershell-verwalten
#
################################################################################

- hosts:              "win_hosts"
  name:               "ONTAP-35-05 - Discover, Login & Mount (Windows)"
  gather_facts:       false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Run PowerShell script with parameters
      ansible.windows.win_powershell:
        script: |
          Get-IscsiTarget
      register: ps_iscsi_targets

    - debug:
        msg: "{{ ps_iscsi_targets }}"


  post_tasks: