################################################################################
#
# Title:        ONTAP-revert-35 - LINUX TEMP
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  Revert all steps performed in test frame 35
#               - iSCSI
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                          "{{ global_primary_linux_host }}"
  name:                           "ONTAP-revert-35 - iSCSI - Linux"
  gather_facts:                   false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.posix

  pre_tasks:

  tasks:
    - name: List iSCSI targets
      community.general.open_iscsi:
        show_nodes:               true
      register: iscsi_nodes

    - name: Remove iSCSI tragets
      community.general.open_iscsi:
        show_nodes:               false
        discover:                 false
        login:                    false
        auto_portal_startup:      false
        auto_node_startup:        false
        target:                   "{{ iscsi_nodes.nodes | unique }}"

  post_tasks: