################################################################################
#
# Title:        ONTAP-01-05 - Cluster Storage 
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Initial cluster configuration for testing
#               - Storage
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "ontap"
  name:               "ONTAP-01-05 - Cluster Storage"
  gather_facts:       false
  vars:
    input: &input
      hostname:       "{{ ansible_host }}"
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
  vars_files:
    - ../vars/labondemand.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Create data aggregates on storage cluster 
    netapp.ontap.na_ontap_aggregate:
      state:                      present
      name:                       "{{ item.name }}"
      nodes:                      "{{ item.node.name }}"
      disks:                      "{{ item.block_storage.primary.disk_count }}"
      snaplock_type:              "{{ item.snaplock_type }}"
      <<: *input 
    loop:
      "{{ storage_aggregates }}"
    loop_control:
      label: "{{ item.node.name }}:{{ item.name }}"
    when:
      - item.name is defined