################################################################################
#
# Title:        ONTAP-35-04 - Discover & Connect
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - LUNs & Mappings
# 
################################################################################

- hosts:                          "{{ global_primary_linux_host }}"
  name:                           "ONTAP-35-04 - Discover & Connect"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - community.general
    - ansible.posix

  pre_tasks:

  tasks:
    - name: Discover iSCSI targets on SVM and login
      community.general.open_iscsi:
        show_nodes:               true
        discover:                 true
        login:                    true
        auto_portal_startup:      true
        auto_node_startup:        true
        portal:                   "{{ item.ip.address }}"
      loop_control:
        label: "{{ item.ip.address }}"
      loop:
        "{{ hostvars[global_primary_test_cluster].network_ip_interfaces |
            selectattr('svm.name', 'defined') |
            selectattr('svm.name', '==', global_primary_san_svm) |
            selectattr('service_policy.name', 'search', 'block') |
            list }}"
    
    - name: Build Filesystem on new LUN
      community.general.filesystem:
        fstype:                   "ext4"
        dev:                      "/dev/dm-2"
  
    - name: Create mount directory
      ansible.builtin.file:
        path:                     "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}"
        state:                    "directory"
        mode:                     "0755"
  
    - name: Mount LUN
      ansible.posix.mount:
        state:                    "mounted"
        src:                      "/dev/dm-2"
        path:                     "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}"
#        opts:                     "rw,sync,hard,vers=3"
        fstype:                   "ext4"
        opts:                     "discard"
  
    - name: Create test file on LUN
      community.general.filesize:
        path: "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}/testfile"
        size: 500MB

  post_tasks: