################################################################################
#
# Title:        ONTAP-revert-00 - Return to Day0 - Linux
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Revert all systems to initial state
#               - Linux
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:              "linux"
  name:               "ONTAP-revert-00 - Return to Day0 - Linux"
  gather_facts:       false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.posix

  tasks:
  - name: Unmount exports
    ansible.posix.mount:
      state:                      "absent"
      src:                        "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/{{ item }}"
      path:                       "{{ linux_31_default_mount_dir }}/{{ item }}"
      opts:                       "rw,sync,hard,vers=3"
      fstype:                     "nfs"
    loop:
      "{{ ontap_31_vol_qtree_names + 
          ontap_31_fg_qtree_names }}"

  - name: Remove mount directories
    ansible.builtin.file:
      path:                       "{{ linux_31_default_mount_dir }}/{{ item }}"
      state:                      "absent"
      mode:                       "0755"
    loop:
      "{{ ontap_31_vol_qtree_names + 
          ontap_31_fg_qtree_names }}"