################################################################################
#
# Title:        ONTAP-37-01 - Subsystem
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-22
# Description:  NVMe/TCP
#               - Subsystem
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                          "{{ global_primary_linux_host }}"
  name:                           "ONTAP-37-01 - Subsystem - Linux"
  gather_facts:                   true
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - community.general
    - ansible.posix

  pre_tasks:

  tasks:

  post_tasks:
  

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-37-01 - Subsystem - ONTAP"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create a Subsystem
      netapp.ontap.na_ontap_nvme_subsystem:
        state:                    present
        vserver:                  "{{ global_primary_san_svm }}"
        name:                     "{{ ontap_37_lin_subsystem_name }}"
        os_type:                  "linux"
        hosts :                   "{{ hostvars[global_primary_linux_host].ansible_hostnqn }}"
        <<: *input

  post_tasks: