################################################################################
#
# Title:        ONTAP-03-03 - Key manager
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Advanced  Cluster Configuration
#               - Key manager
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "ontap"
  name:               "ONTAP-03-03 - Key manager"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Configure onboard Key Manager
    netapp.ontap.na_ontap_security_key_manager:
      state:                      present
      onboard:
        passphrase:               "{{ security_key_managers.onboard.passphrase }}"
      <<: *input
    when:
      security_key_managers.onboard is defined
    register:
      ontap_onboard_key_backup

  - name: Display key backup
    ansible.builtin.debug:
      msg:
        - "This is the ONTAP onboard backup key:\n"
        - "{{ ontap_onboard_key_backup }}"