################################################################################
#
# Title:        ONTAP-35-03 - LUNs & Mappings
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - LUNs & Mappings
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-35-02 - Volumes"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create LUN for Linux host
      netapp.ontap.na_ontap_lun:
        state:                      present
        vserver:                    "{{ global_primary_san_svm }}"
        name:                       "{{ ontap_35_lin_lun_name }}"
        flexvol_name:               "{{ ontap_35_lin_vol_name }}"
        size:                       "{{ ontap_default_lun_size_gb }}"
        size_unit:                  "gb"
        os_type:                    "linux"
        space_reserve:              true
        <<: *input

    - name: Create LUN for Windows host
      netapp.ontap.na_ontap_lun:
        state:                      present
        vserver:                    "{{ global_primary_san_svm }}"
        name:                       "{{ ontap_35_win_lun_name }}"
        flexvol_name:               "{{ ontap_35_win_vol_name }}"
        size:                       "{{ ontap_default_lun_size_gb }}"
        size_unit:                  "gb"
        os_type:                    "windows"
        space_reserve:              true
        <<: *input

    - name: Map LUN to Linux iGroup
      netapp.ontap.na_ontap_lun:
        state:                      present
        vserver:                    "{{ global_primary_san_svm }}"
        initiator_group_name:       "{{ ontap_35_lin_igroup_name }}"
        path:                       "/vol/{{ ontap_35_lin_vol_name }}/{{ ontap_35_lin_lun_name }}"
        <<: *input

    - name: Map LUN to Windows iGroup
      netapp.ontap.na_ontap_lun:
        state:                      present
        vserver:                    "{{ global_primary_san_svm }}"
        initiator_group_name:       "{{ ontap_35_win_igroup_name }}"
        path:                       "/vol/{{ ontap_35_win_vol_name }}/{{ ontap_35_win_lun_name }}"
        <<: *input

  post_tasks: