################################################################################
#
# Title:        ONTAP-35-05 - Discover, Login & Mount (Windows)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-31
# Description:  CIFS
#               - Mount & Write (Volume)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "win_hosts"
  name:               "ONTAP-35-05 - Discover, Login & Mount (Windows)"
  gather_facts:       false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: Get iSCSI targets
      ansible.windows.win_command:
        "iscsicli ListTargets"
      register: iscsi_targets

    - debug:
        msg: "{{ iscsi_targets }}"

  post_tasks: