################################################################################
#
# Title:        ONTAP-41-07 - Flexclone Volumes
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-10
# Description:  NFS Flexclone
#               - Make Many Volumes & Mount
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-41-07 - Make Many Volumes & Mount"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:
    # - name: Get and Set Ansible date_time fact
    #   set_fact:
    #     pipe_timestamp: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"

  tasks:

    # - name: Create Volume clone (Flexclone) - "{{ ontap_41_snapshot_name }}"
    #   netapp.ontap.na_ontap_volume_clone:
    #     state:                      present
    #     vserver:                    "{{ global_primary_nas_svm }}"
    #     parent_volume:              "{{ ontap_41_vol_name }}"
    #     name:                       "{{ ontap_41_clone_vol_name}}"
    #     parent_snapshot:            "{{ ontap_41_snapshot_name }}"
    #     junction_path:              "/{{ ontap_41_clone_dir_name }}/{{ ontap_41_clone_vol_name }}"
    #     <<: *input

    # - name: Output from index_var
    #   ansible.builtin.debug:
    #     # msg: "{{ ontap_41_clone_vol_name }}_{{ '%02x' | format(item) }}"
    #     msg: "{{ ontap_41_clone_vol_name }}_{{ '%02x' | format(my_idx + 1) }}"
    #   loop: "{{ range(1, 10) | list }}"
    #   loop_control:
    #     index_var: my_idx

    - name: Create & NFS Mount Clone of Source
      include_tasks: client_copy_n_mount.yml
      loop: "{{ range(1, 10) | list }}"
      loop_control:
        index_var: idx
  
  post_tasks: