################################################################################
#
# Title:        ONTAP-20-01 - Storage Virtual Machines (SVMs)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-22
# Description:  Basic SVM Setup
#               - Storage Virtual Machines (SVMs)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-20-01 - Storage Virtual Machines (SVMs)"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
  - name: Create all SVMs for testing on "{{ global_primary_test_cluster }}"
    netapp.ontap.na_ontap_svm:
      state:                      present
      name:                       "{{ item.name }}"
      services:
        cifs:
          allowed:                "{{ item.cifs.allowed | default(omit) }}"
        ndmp:
          allowed:                "{{ item.ndmp.allowed | default(omit) }}"
        nfs:
          allowed:                "{{ item.nfs.allowed | default(omit) }}"
          enabled:                "{{ item.nfs.enabled | default(omit) }}"
        fcp:
          allowed:                "{{ item.fcp.allowed | default(omit) }}"
          enabled:                "{{ item.fcp.enabled | default(omit) }}"
        iscsi:
          allowed:                "{{ item.iscsi.allowed | default(omit) }}"
          enabled:                "{{ item.iscsi.enabled | default(omit) }}"
        nvme:
          allowed:                "{{ item.nvme.allowed | default(omit) }}"
          enabled:                "{{ item.nvme.enabled | default(omit) }}"
      <<: *input
    loop:
      "{{ svm_svms }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - svm_svms | length > 0
      - item.name is defined 
      - security_authentication_cluster_ad_proxy.svm.name is defined and
        security_authentication_cluster_ad_proxy.svm.name != item.name

  - name: Patch additional SVM parameters - auto_enable_analytics
    netapp.ontap.na_ontap_rest_cli:
      command:                    'vserver'
      verb:                       'PATCH'
      params: 
        vserver:                  "{{ item.name }}"
      body:
        auto_enable_analytics:    "{{ item.auto_enable_analytics }}"
      <<: *input
    loop:
      "{{ svm_svms }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - svm_svms | length > 0
      - item.name is defined
      - item.auto_enable_analytics is defined
      - security_authentication_cluster_ad_proxy.svm.name is defined and
        security_authentication_cluster_ad_proxy.svm.name != item.name

  - name: Patch additional SVM parameters - auto_enable_activity_tracking
    netapp.ontap.na_ontap_rest_cli:
      command:                    'vserver'
      verb:                       'PATCH'
      params: 
        vserver:                  "{{ item.name }}"
      body:
        auto_enable_activity_tracking: "{{ auto_enable_activity_tracking }}"
      <<: *input
    loop:
      "{{ svm_svms }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - svm_svms | length > 0
      - item.name is defined
      - item.auto_enable_activity_tracking is defined
      - security_authentication_cluster_ad_proxy.svm.name is defined and
        security_authentication_cluster_ad_proxy.svm.name != item.name

  post_tasks: