################################################################################
#
# Title:        ONTAP-41-07- Client Write (flexclone volume)
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2023-10-08
# Description:  NFS Flexclone
#               - Client Write (flexclone volume)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "linux"
  name:               "ONTAP-41-07 - Client Write (Flexclone Volume)"
  gather_facts:       false
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:
    - name: Get and Set Ansible date_time fact
      set_fact:
        pipe_timestamp: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"

  tasks:
    - name: Create test file on each export
      community.general.filesize:
        path: "{{ linux_default_mount_dir }}/{{ ontap_41_clone_dir_name }}/{{ ontap_41_clone_vol_name }}/extraop_{{ pipe_timestamp }}"
        size: "{{ filesize | default('500MB') }}"
  
  post_tasks: