################################################################################
#
# Title:        ONTAP-35-04 - Discover, Login & Mount (Linux)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-10-30
# Description:  iSCSI
#               - Discover, Login & Mount (Linux)
# 
# https://kb.netapp.com/onprem/ontap/da/SAN/How_to_match_Linux_disk_WWID_to_LUN_serial_number
# 
################################################################################

- hosts:                          "{{ global_primary_test_cluster }}"
  name:                           "ONTAP-35-04 - Discover, Login & Mount (Linux) - ONTAP"
  gather_facts:                   false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Get LUNs from "{{ global_primary_san_svm }}"
      netapp.ontap.na_ontap_rest_info:
        gather_subset:
          - "storage/luns"
        fields:
          - "svm"
          - "location"
          - "serial_number"
        parameters:
          svm.name:               "{{ global_primary_san_svm }}"
        use_python_keys:          true
        <<: *input
      register: lun_info

  post_tasks:

- hosts:                          "{{ global_primary_linux_host }}"
  name:                           "ONTAP-35-04 - Discover, Login & Mount (Linux) - Linux"
  gather_facts:                   false
  vars:
    ntap_iscsi_vendor_id:         "3600a0980"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - community.general
    - ansible.posix

  pre_tasks:

  tasks:
    - debug:
        msg: "{{ hostvars[global_primary_test_cluster].lun_info }}"

    - name: Discover iSCSI targets on SVM and login
      community.general.open_iscsi:
        show_nodes:               true
        discover:                 true
        login:                    true
        auto_portal_startup:      true
        auto_node_startup:        true
        portal:                   "{{ item.ip.address }}"
      loop_control:
        label: "{{ item.ip.address }}"
      loop:
        "{{ hostvars[global_primary_test_cluster].network_ip_interfaces |
            selectattr('svm.name', 'defined') |
            selectattr('svm.name', '==', global_primary_san_svm) |
            selectattr('service_policy.name', 'search', 'block') |
            list }}"
    
    - name: Build Filesystem on new LUN
      community.general.filesystem:
        fstype:                   "ext4"
        dev:                      "/dev/{{ ntap_iscsi_vendor_id }}
                                   {{ (hostvars[global_primary_test_cluster].lun_info.ontap_info.storage_luns.records |
                                      selectattr('name', 'defined') |
                                      selectattr('name', '==', '/vol/'+ontap_35_lin_vol_name+'/'+ontap_35_lin_lun01)).serial_hex }}"
  
    - name: Create mount directory  
      ansible.builtin.file:
        path:                     "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}"
        state:                    "directory"
        mode:                     "0755"
  
    - name: Mount LUN
      ansible.posix.mount:
        state:                    "mounted"
        src:                      "/dev/dm-2"
        path:                     "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}"
#        opts:                     "rw,sync,hard,vers=3"
        fstype:                   "ext4"
        opts:                     "discard"
  
    - name: Create test file on LUN
      community.general.filesize:
        path: "{{ linux_35_default_mount_dir }}/{{ ontap_35_lin_lun_name }}/testfile"
        size: 500MB

  post_tasks: