- hosts:              "ontap"
  name:               ONTAP-00-01 - Cluster Network Config
  gather_facts:       false
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
    member_ports:
      - name:                   "e1f"
      - name:                   "e1g"
    security_accounts:
      - name:                         "na_local_admin"
        scope:                        "cluster"
        owner:
          name:
        locked:                       false
        applications:
          - application:              "ssh"
            authentication_methods:
              - "password"
            second_authentication_method: "none"
          - application:              "ontapi"
            authentication_methods:
              - "password"
            second_authentication_method: "none"
          - application:              "http"
            authentication_methods:
              - "password"
            second_authentication_method: "none"
        comment:                      "Local user with admin privileges for testing"
        role:
          name:                       "admin"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  tasks:
    - name: test debug
      ansible.builtin.debug:
        msg: "{{ security_accounts[0].applications | map(attribute='authentication_methods') | flatten }}"

    - name: test debug hosts
      ansible.builtin.debug:
        msg: "{{ hostvars['linux'] }}"

    - name: test debug hosts
      ansible.builtin.debug:
        msg: "{{ hostvars['linux'] | map(attribute='ansible_host') | flatten }}"