- hosts:              "ontap"
  name:               ONTAP - TEST
  gather_facts:       false
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
    protocols_active_directory:
      ntap-svm01-nas:
        preferred-domain-controllers:
          - fqdn:                    "demo.netapp.com"
            ip:                      "192.168.0.252"
          - fqdn:                    "demo.netapp.com"
            ip:                      "192.168.0.253"
      ntap-svm02-san:
        preferred-domain-controllers:
          - fqdn:                    "demo.netapp.com"
            ip:                      "192.168.0.252"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  tasks:
    - name: test debug
      ansible.builtin.debug:
        msg: "{{ protocols_active_directorys | map(attribute='preferred-domain-controllers') | flatten }}"

#    - name: test debug hosts
#      ansible.builtin.debug:
#        msg: "{{ storage_aggregates | map(attribute='name') | flatten }}"

#    - name: test debug hosts
#      ansible.builtin.debug:
#        msg: "{{ groups['linux'] | map('extract', hostvars, ['ansible_host']) }}"