- hosts:              "{{ ontap_primary_cluster }}"
  name:               ONTAP-00-01 - Cluster Network Config
  gather_facts:       false
  vars_prompt:
    - name:           testenv_ad_join_pw
      prompt:         "Please enter password for user  {{ testenv_ad_join_user }}"
      private:        true
  vars:
    input: &input
      username:       "{{ ontap_admin_user }}"
      password:       "{{ ontap_admin_password }}"
      https:          true
      validate_certs: false
      use_rest:       "always"
    member_ports:
      - name:                   "e1f"
      - name:                   "e1g"
  vars_files:
    - ../vars/labondemand.yml
  collections:
    - netapp.ontap

  tasks:
    - name: test debug
      ansible.builtin.debug:
        msg: "{{ member_ports | map(attribute='name') | flatten }}"