################################################################################
#
# Title:        ONTAP-32-05 - Shares & ACLs (FlexGroup)
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-24
# Description:  CIFS
#               - Shares & ACLs (FlexGroup)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-32-05 - Shares & ACLs (FlexGroup)"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create shares
      netapp.ontap.na_ontap_cifs:
        state:                         present
        name:                          "{{ item }}"
        path:                          "/{{ ontap_32_fg_name }}/{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        browsable:                     true
        oplocks:                       true
        show_snapshot:                 true
        comment:                       "Test share created as part of test frame ONTAP-22"
        <<: *input
      loop:
        "{{ ontap_32_fg_qtree_names }}"

    - name: Remove "Full Control" for "Everyone"
      netapp.ontap.na_ontap_cifs_acl:
        state:                         absent
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "Everyone"
        permission:                    "full_control"
        <<: *input
      loop:
        "{{ ontap_32_fg_qtree_names }}"

    - name: Create ACL on test share (admins - Full Control)
      netapp.ontap.na_ontap_cifs_acl:
        state:                         present
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "{{ ontap_32_ad_admin_group }}"
        permission:                    "full_control"
        <<: *input
      loop:
        "{{ ontap_32_fg_qtree_names }}"

    - name: Create ACL on test share (read-only users - Read)
      netapp.ontap.na_ontap_cifs_acl:
        state:                         present
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "{{ ontap_32_ad_ro_group }}"
        permission:                    "read"
        <<: *input
      loop:
        "{{ ontap_32_fg_qtree_names }}"
  
  post_tasks: