################################################################################
#
# Title:        ONTAP-32-04 - FlexGroups & Qtrees
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-24
# Description:  CIFS
#               - FlexGroup & qtrees
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_cluster"
  name:                                "ONTAP-32-04 - FlexGroups & Qtrees"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create FlexGroup
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ ontap_32_fg_name }}"
        size:                          "{{ ontap_default_fg_size_gb }}"
        volume_security_style:         "ntfs"
        aggr_list:                     "{{ storage_aggregates | map(attribute='name') | flatten }}"
        aggr_list_multiplier:          "{{ ontap_default_fg_multiplier }}"
        size_unit:                     gb
        space_guarantee:               "none"
        tiering_policy:                "auto"
        junction_path:                 "/{{ ontap_32_fg_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        wait_for_completion:           True
        <<: *input
  
    - name: Create qtrees
      netapp.ontap.na_ontap_qtree:
        state:                         present
        name:                          "{{ item }}"
        flexvol_name:                  "{{ ontap_32_fg_name }}"
        security_style:                "ntfs"
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input
      loop:
        "{{ ontap_32_fg_qtree_names }}"
  
  post_tasks: