################################################################################
#
# Title:        ONTAP-82-03 - Activate and train Anti-ransomware
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-11-04
# Description:  Anti-Ransomware
#               - Mount & Write
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-82-03 - Dry-run Anti-ransomware"
  gather_facts:                        false
  vars:
    input01: &input01
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
#    - name: Start  Anti-ransomware dry-run on volumes
#      netapp.ontap.na_ontap_rest_cli:
#        command:                       'security/anti-ransomware/volume/dry-run'
#        verb:                          'POST'
#        params:
#        body:
#          vserver:                     "{{ item.0 }}"
#          volume:                      "{{ item.1 }}"
#        <<: *input01
#      loop:
#        "{{ ontap_82_tenant_list | product(ontap_82_volumes) | list }}"
#      ignore_errors:                   true

- hosts:                               "linux"
  name:                                "ONTAP-82-03 - Write Data"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:

  tasks:
    - name: Create test files on exports
      ansible.builtin.script: ./scripts/ONTAP-82-03.sh "{{ linux_82_mount_dir }}/{{ item.0 }}/{{ item.1 }}_{{ item.2 }}" 1000
      loop:
        "{{ ontap_82_tenant_list | product(ontap_82_volumes, ontap_82_qtrees) | list }}"
  
  post_tasks:

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-82-03 - Activate Anti-ransomware"
  gather_facts:                        false
  vars:
    input02: &input02
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Start  Anti-ransomware dry-run on volumes
      netapp.ontap.na_ontap_rest_cli:
        command:                       'security/anti-ransomware/volume/enable'
        verb:                          'POST'
        params:
        body:
          vserver:                     "{{ item.0 }}"
          volume:                      "{{ item.1 }}"
        <<: *input02
      loop:
        "{{ ontap_82_tenant_list | product(ontap_82_volumes) | list }}"
      ignore_errors:                   true

    - name: Activate additional notifications for ransomware events
      netapp.ontap.na_ontap_rest_cli:
        command:                       'security/anti-ransomware/volume/event-log'
        verb:                          'PATCH'
        params:
          vserver:                     "{{ item.0 }}"
          volume:                      "{{ item.1 }}"
        body:
          is-enabled-on-new-file-extension-seen:
                                       true
          is-enabled-on-snapshot-copy-creation:
                                       true
        <<: *input01
      loop:
        "{{ ontap_82_tenant_list | product(ontap_82_volumes) | list }}"