################################################################################
#
# Title:        ONTAP-82-04 - Simulate Attack
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-11-04
# Description:  Anti-Ransomware
#               - Simulate Attack
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "linux"
  name:                                "ONTAP-82-04 - Simulate Attack"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix
    - community.general

  pre_tasks:

  tasks:
    - name: Encrypt and rename files
      ansible.builtin.script: ./scripts/ONTAP-82-04.sh "{{ linux_82_mount_dir }}/{{ item.0 }}/{{ item.1 }}_{{ item.2 }}"
      loop:
        "{{ ontap_80_svms | product(ontap_80_volumes, ontap_82_qtrees) | list }}"
  
  post_tasks: