################################################################################
#
# Title:        ONTAP-82-02 - Configure Events
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2024-11-04
# Description:  Anti-Ransomware
#               - Configure Events
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-82-02 - Configure Events"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Configure EMS filters for every tenant
      netapp.ontap.na_ontap_ems_filter:
        state:                         "present"
        name:                          "ems_{{ item }}"
        rules:                         []
        <<: *input
      loop:
        "{{ ontap_80_svms }}"

    - name: Add EMS filter to match tenant only
      netapp.ontap.na_ontap_rest_cli:
        command:                       'event/filter/rule/add'
        verb:                          'POST'
        params:
        body:
          filter-name:                 "ems_{{ item }}"
          type:                        "include"
          position:                    1
          message-name:                "arw.*"
          severity:
            - "*"
          parameter-criteria:
            - "vserverName={{ item }}"
        <<: *input
      loop:
        "{{ ontap_80_svms }}"

    - name: Configure REST EMS destination for every tenant
      netapp.ontap.na_ontap_ems_destination:
        state:                         "present"
        name:                          "dest_{{ item }}"
        type:                          "{{ ontap_82_ems_dest_type }}"
        filters:                       "ems_{{ item }}"
        destination:                   "{{ ontap_82_ems_dest_destination }}{{ item }}"
        <<: *input
      loop:
        "{{ ontap_80_svms }}"

  post_tasks: