ansible_connection:               "local"
ansible_python_interpreter:       "{{ansible_playbook_python}}"

security_login_messages:
  - banner: |
      ################ TEST BANNER ################
      # This system is currently in testing state #
      #############################################
    scope:                        "cluster"
    message: |                     
      Welcome! Please note:
      This system is not ready for production yet!
      
network_ethernet_broadcast_domains:
  - name:                         "bc_data"
    ipspace:
      name:                       "Default"
    mtu:                          1500

security_key_managers:
  onboard:
    passphrase:                   "{{ vault_security_key_managers.onboard.passphrase }}"