# Ansible Variables
ansible_connection:               "local"
ansible_python_interpreter:       "{{ansible_playbook_python}}"

# Custom Variables

# Variables basedon ONTAP REST model
# https://<ontap_cluster_mgmt>/docs/api
security_login_messages:
  - banner: |
      ################ TEST BANNER ################
      # This system is currently in testing state #
      #############################################
    scope:                        "cluster"
    message: |                     
      Welcome! Please note:
      This system is not ready for production yet!
      
network_ethernet_broadcast_domains:
  - name:                         "bc_data"
    ipspace:
      name:                       "Default"
    mtu:                          1500

security_key_managers:
  onboard:
    passphrase:                   "{{ vault_security_key_managers.onboard.passphrase }}"

security_accounts:
  - name:                         "ontap_local_admin_user"
    owner:
      name:
    locked:                       false
    applications:
      - application:              "ssh"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_admin_user.password }}"
      - application:              "ontapi"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_admin_user.password }}"
      - application:              "http"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_admin_user.password }}"
    comment:                      "Local user with admin privileges for testing"
    role:
      name:                       "admin"
  - name:                         "ontap_local_ro_user"
    owner:
      name:
    locked:                       false
    applications:
      - application:              "ssh"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_ro_user.password }}"
      - application:              "ontapi"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_ro_user.password }}"
      - application:              "http"
        authentication_methods:
          - "password"
        second_authentication_method: "none"
        password:                 "{{ vault_security_accounts.ontap_local_ro_user.password }}"
    comment:                      "Local user with read-only privileges for testing"
    role:
      name:                       "readonly"
