vault_security_key_managers:
  onboard:
    passphrase:                   "ThisPassphraseIsUsedForPoCTestingToAllowVolEncryption"

# ATTENTION - not following standard ONTAP REST model here for passwords
# but it is more practical...
vault_security_accounts:
  ontap_local_admin_user:
    password:                     "CustomTest1!"
  ontap_local_ro_user:
    password:                     "CustomTest2!"