################################################################################
#
# Title:        ONTAP-revert-31 - NFS
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-17
# Description:  Revert all steps performed in test frame 31
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "linux"
  name:                                "ONTAP-revert-31 - NFS - Linux"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix

  tasks:
    - name: Unmount exports on volume
      ansible.posix.mount:
        state:                         "absent"
        src:                           "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/{{ ontap_31_vol_name }}/{{ item }}"
        path:                          "{{ linux_31_mount_dir }}/{{ item }}"
#        opts:                          "rw,sync,hard,vers=3"
        fstype:                        "nfs"
      loop:
        "{{ ontap_31_vol_qtree_names }}"
  
    - name: Unmount exports on FlexGroup
      ansible.posix.mount:
        state:                         "absent"
        src:                           "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/{{ ontap_31_fg_qtree_names }}/{{ item }}"
        path:                          "{{ linux_31_mount_dir }}/{{ item }}"
#        opts:                          "rw,sync,hard,vers=3"
        fstype:                        "nfs"
      loop:
        "{{ ontap_31_fg_qtree_names }}"
  
    - name: Remove mount directories
      ansible.builtin.file:
        path:                          "{{ linux_31_mount_dir }}/{{ item }}"
        state:                         "absent"
        mode:                          "0755"
      loop:
        "{{ ontap_31_vol_qtree_names + 
            ontap_31_fg_qtree_names }}"

    - name: Remove default parent mount directory
      ansible.builtin.file:
        path:                          "{{ linux_31_mount_dir }}"
        state:                         "absent"
        mode:                          "0755"

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-revert-31 - NFS - ONTAP"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  tasks:
    - name: Remove volume
      netapp.ontap.na_ontap_volume:
        state:                         absent
        name:                          "{{ ontap_31_vol_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
  
    - name: Remove FlexGroup
      netapp.ontap.na_ontap_volume:
        state:                         absent
        name:                          "{{ ontap_31_fg_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
  
    - name: Remove read-write export policy
      netapp.ontap.na_ontap_export_policy:
        state:                         absent
        name:                          "{{ ontap_31_policy_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"