################################################################################
#
# Title:        ONTAP-31-02 - Volumes & Qtrees
# Author:       NetApp Inc. (badrian)
# Initial 
# Create Date:  2023-08-22
# Description:  NFS
#               - Volumes & Qtrees
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_cluster"
  name:                                "ONTAP-31-02 - Volumes & Qtrees"
  gather_facts:                        false
  vars:
    input: &input
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create volume
      netapp.ontap.na_ontap_volume:
        state:                         present
        name:                          "{{ ontap_31_vol_name }}"
        aggregate_name:                "{{ hostvars['primary_storage_cluster'].storage_aggregates[0].name }}"
        size:                          "{{ ontap_default_vol_size_gb }}"
        size_unit:                     gb
        space_guarantee:               none
        tiering_policy:                auto
        export_policy:                 "ro_{{ global_primary_nas_svm }}"
        junction_path:                 "/{{ ontap_31_vol_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        volume_security_style:         "unix"
        <<: *input
  
    - name: Create qtrees
      netapp.ontap.na_ontap_qtree:
        state:                         present
        name:                          "{{ item }}"
        flexvol_name:                  "{{ ontap_31_vol_name }}"
        export_policy:                 "{{ ontap_31_policy_name }}"
        security_style:                "unix"
        unix_permissions:              0777
        vserver:                       "{{ global_primary_nas_svm }}"
        <<: *input
      loop:
        "{{ ontap_31_vol_qtree_names }}"
  
  post_tasks: